// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2d_stream_data_to_axis (
        ap_ready,
        x,
        last,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [31:0] x;
input  [0:0] last;
output  [0:0] ap_return_0;
output  [31:0] ap_return_1;

assign ap_ready = 1'b1;

assign ap_return_0 = last;

assign ap_return_1 = x;

endmodule //conv2d_stream_data_to_axis
