-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_stream_conv2d_stream,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.039000,HLS_SYN_LAT=244614,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1156,HLS_SYN_LUT=1474,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv7_44 : STD_LOGIC_VECTOR (6 downto 0) := "1000100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_42 : STD_LOGIC_VECTOR (6 downto 0) := "1000010";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv8_88 : STD_LOGIC_VECTOR (7 downto 0) := "10001000";
    constant ap_const_lv13_1103 : STD_LOGIC_VECTOR (12 downto 0) := "1000100000011";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv8_44 : STD_LOGIC_VECTOR (7 downto 0) := "01000100";
    constant ap_const_lv13_42 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal k00 : STD_LOGIC_VECTOR (31 downto 0);
    signal k01 : STD_LOGIC_VECTOR (31 downto 0);
    signal k02 : STD_LOGIC_VECTOR (31 downto 0);
    signal k10 : STD_LOGIC_VECTOR (31 downto 0);
    signal k11 : STD_LOGIC_VECTOR (31 downto 0);
    signal k12 : STD_LOGIC_VECTOR (31 downto 0);
    signal k20 : STD_LOGIC_VECTOR (31 downto 0);
    signal k21 : STD_LOGIC_VECTOR (31 downto 0);
    signal k22 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln69_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_629_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln80_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal k22_read_reg_873 : STD_LOGIC_VECTOR (31 downto 0);
    signal k21_read_reg_878 : STD_LOGIC_VECTOR (31 downto 0);
    signal k20_read_reg_883 : STD_LOGIC_VECTOR (31 downto 0);
    signal k12_read_reg_888 : STD_LOGIC_VECTOR (31 downto 0);
    signal k11_read_reg_893 : STD_LOGIC_VECTOR (31 downto 0);
    signal k10_read_reg_898 : STD_LOGIC_VECTOR (31 downto 0);
    signal k02_read_reg_903 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln60_fu_541_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln60_reg_908 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln57_fu_553_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln57_reg_916 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln59_fu_589_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal img_r_2_fu_611_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal img_r_2_reg_949 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln69_1_fu_623_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln69_1_reg_957 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_predicate_op138_read_state9 : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal add_ln1171_fu_687_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1171_reg_965 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln1169_fu_693_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln1169_reg_970 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln80_fu_705_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln80_reg_978 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state10 : BOOLEAN;
    signal ap_block_state10_io : BOOLEAN;
    signal out_count_4_fu_718_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal out_count_4_reg_988 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal add_ln82_fu_748_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln82_reg_1001 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln82_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kernel_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_reg_1011 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal linebuf_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_load_2_reg_1016 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_780_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_1_reg_1031 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal linebuf_V_addr_2_reg_1041 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal linebuf_V_addr_3_reg_1046 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln94_fu_846_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln94_reg_1059 : STD_LOGIC_VECTOR (6 downto 0);
    signal linebuf_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_V_ce0 : STD_LOGIC;
    signal linebuf_V_we0 : STD_LOGIC;
    signal linebuf_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_V_ce1 : STD_LOGIC;
    signal linebuf_V_we1 : STD_LOGIC;
    signal linebuf_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal kernel_V_ce0 : STD_LOGIC;
    signal kernel_V_we0 : STD_LOGIC;
    signal kernel_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_V_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal kernel_V_ce1 : STD_LOGIC;
    signal kernel_V_we1 : STD_LOGIC;
    signal kernel_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_reg_421 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln57_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptr_reg_432 : STD_LOGIC_VECTOR (6 downto 0);
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln67_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_count_1_reg_444 : STD_LOGIC_VECTOR (12 downto 0);
    signal kr_reg_454 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_V_reg_465 : STD_LOGIC_VECTOR (31 downto 0);
    signal kc_reg_479 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_V_3_reg_490 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_reg_502 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln60_2_fu_578_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_1_fu_658_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1169_1_fu_733_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1171_3_fu_769_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln95_1_fu_824_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_fu_809_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln96_fu_835_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_172 : STD_LOGIC_VECTOR (1 downto 0);
    signal img_r_fu_184 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln94_fu_840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_count_fu_188 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln69_fu_852_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_529_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_521_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln60_fu_537_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln60_1_fu_569_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln60_1_fu_573_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_fu_642_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln76_fu_648_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_1_fu_652_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_675_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_667_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1171_1_fu_683_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1171_fu_663_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln1169_fu_724_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1169_fu_728_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln82_fu_738_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln83_fu_754_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1171_2_fu_760_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1171_1_fu_764_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_1_fu_786_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_794_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln95_fu_814_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln95_fu_818_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln96_fu_829_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_mul_32s_32s_48_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component conv2d_stream_linebuf_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_kernel_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        k00 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k01 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k02 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k20 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k21 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k22 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    linebuf_V_U : component conv2d_stream_linebuf_V
    generic map (
        DataWidth => 32,
        AddressRange => 204,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => linebuf_V_address0,
        ce0 => linebuf_V_ce0,
        we0 => linebuf_V_we0,
        d0 => linebuf_V_d0,
        q0 => linebuf_V_q0,
        address1 => linebuf_V_address1,
        ce1 => linebuf_V_ce1,
        we1 => linebuf_V_we1,
        d1 => linebuf_V_q0,
        q1 => linebuf_V_q1);

    kernel_V_U : component conv2d_stream_kernel_V
    generic map (
        DataWidth => 32,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => kernel_V_address0,
        ce0 => kernel_V_ce0,
        we0 => kernel_V_we0,
        d0 => kernel_V_d0,
        address1 => kernel_V_address1,
        ce1 => kernel_V_ce1,
        we1 => kernel_V_we1,
        d1 => kernel_V_d1,
        q1 => kernel_V_q1);

    CTRL_s_axi_U : component conv2d_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        k00 => k00,
        k01 => k01,
        k02 => k02,
        k10 => k10,
        k11 => k11,
        k12 => k12,
        k20 => k20,
        k21 => k21,
        k22 => k22,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32s_32s_48_2_1_U1 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => linebuf_V_load_2_reg_1016,
        din1 => r_V_reg_1011,
        ce => ap_const_logic_1,
        dout => grp_fu_780_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => acc_V_reg_465,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    acc_V_3_reg_490_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                acc_V_3_reg_490 <= ret_V_fu_794_p2(47 downto 16);
            elsif ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln80_fu_699_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                acc_V_3_reg_490 <= acc_V_reg_465;
            end if; 
        end if;
    end process;

    acc_V_reg_465_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                acc_V_reg_465 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln82_fu_742_p2 = ap_const_lv1_1))) then 
                acc_V_reg_465 <= acc_V_3_reg_490;
            end if; 
        end if;
    end process;

    c_1_reg_502_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (icmp_ln69_fu_617_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                c_1_reg_502 <= ap_const_lv7_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                c_1_reg_502 <= add_ln94_reg_1059;
            end if; 
        end if;
    end process;

    c_reg_421_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln59_fu_583_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                c_reg_421 <= add_ln59_fu_589_p2;
            elsif (((icmp_ln57_fu_547_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                c_reg_421 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    img_r_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln57_fu_547_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                img_r_fu_184 <= ap_const_lv7_0;
            elsif (((icmp_ln94_fu_840_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                img_r_fu_184 <= img_r_2_reg_949;
            end if; 
        end if;
    end process;

    kc_reg_479_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                kc_reg_479 <= add_ln82_reg_1001;
            elsif ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln80_fu_699_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                kc_reg_479 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kr_reg_454_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                kr_reg_454 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln82_fu_742_p2 = ap_const_lv1_1))) then 
                kr_reg_454 <= add_ln80_reg_978;
            end if; 
        end if;
    end process;

    out_count_1_reg_444_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                out_count_1_reg_444 <= out_count_4_reg_988;
            elsif (((icmp_ln67_fu_605_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                out_count_1_reg_444 <= out_count_fu_188;
            end if; 
        end if;
    end process;

    out_count_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln57_fu_547_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                out_count_fu_188 <= ap_const_lv13_0;
            elsif (((icmp_ln94_fu_840_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                out_count_fu_188 <= add_ln69_fu_852_p2;
            end if; 
        end if;
    end process;

    ptr_reg_432_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                ptr_reg_432 <= add_ln69_1_reg_957;
            elsif (((icmp_ln67_fu_605_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                ptr_reg_432 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    r_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_fu_172 <= ap_const_lv2_0;
            elsif (((icmp_ln59_fu_583_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                r_fu_172 <= add_ln57_reg_916;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                    add_ln1171_reg_965(7 downto 2) <= add_ln1171_fu_687_p2(7 downto 2);
                sub_ln1169_reg_970 <= sub_ln1169_fu_693_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln57_reg_916 <= add_ln57_fu_553_p2;
                    add_ln60_reg_908(7 downto 2) <= add_ln60_fu_541_p2(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                add_ln69_1_reg_957 <= add_ln69_1_fu_623_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                add_ln80_reg_978 <= add_ln80_fu_705_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                add_ln82_reg_1001 <= add_ln82_fu_748_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                add_ln94_reg_1059 <= add_ln94_fu_846_p2;
                linebuf_V_addr_2_reg_1041 <= zext_ln95_1_fu_824_p1(8 - 1 downto 0);
                    linebuf_V_addr_3_reg_1046(6 downto 0) <= zext_ln94_fu_809_p1(8 - 1 downto 0)(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                img_r_2_reg_949 <= img_r_2_fu_611_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                k02_read_reg_903 <= k02;
                k10_read_reg_898 <= k10;
                k11_read_reg_893 <= k11;
                k12_read_reg_888 <= k12;
                k20_read_reg_883 <= k20;
                k21_read_reg_878 <= k21;
                k22_read_reg_873 <= k22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                linebuf_V_load_2_reg_1016 <= linebuf_V_q0;
                r_V_reg_1011 <= kernel_V_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_count_4_reg_988 <= out_count_4_fu_718_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                r_V_1_reg_1031 <= grp_fu_780_p2;
            end if;
        end if;
    end process;
    add_ln60_reg_908(1 downto 0) <= "00";
    add_ln1171_reg_965(1 downto 0) <= "00";
    linebuf_V_addr_3_reg_1046(7) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state9, icmp_ln69_fu_617_p2, ap_CS_fsm_state10, icmp_ln80_fu_699_p2, ap_CS_fsm_state16, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_predicate_op138_read_state9, ap_block_state10_io, ap_CS_fsm_state11, icmp_ln82_fu_742_p2, ap_CS_fsm_state17, icmp_ln57_fu_547_p2, icmp_ln59_fu_583_p2, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln67_fu_605_p2, icmp_ln94_fu_840_p2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln57_fu_547_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln59_fu_583_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((icmp_ln67_fu_605_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln67_fu_605_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (icmp_ln69_fu_617_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                elsif ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln80_fu_699_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln82_fu_742_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state16 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln94_fu_840_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln1169_fu_728_p2 <= std_logic_vector(unsigned(sub_ln1169_reg_970) + unsigned(zext_ln1169_fu_724_p1));
    add_ln1171_1_fu_764_p2 <= std_logic_vector(unsigned(add_ln1171_reg_965) + unsigned(zext_ln1171_2_fu_760_p1));
    add_ln1171_fu_687_p2 <= std_logic_vector(unsigned(tmp_7_fu_667_p3) + unsigned(zext_ln1171_1_fu_683_p1));
    add_ln57_fu_553_p2 <= std_logic_vector(unsigned(r_fu_172) + unsigned(ap_const_lv2_1));
    add_ln59_fu_589_p2 <= std_logic_vector(unsigned(c_reg_421) + unsigned(ap_const_lv7_1));
    add_ln60_1_fu_573_p2 <= std_logic_vector(unsigned(add_ln60_reg_908) + unsigned(zext_ln60_1_fu_569_p1));
    add_ln60_fu_541_p2 <= std_logic_vector(unsigned(tmp_fu_521_p3) + unsigned(zext_ln60_fu_537_p1));
    add_ln69_1_fu_623_p2 <= std_logic_vector(unsigned(ptr_reg_432) + unsigned(ap_const_lv7_1));
    add_ln69_fu_852_p2 <= std_logic_vector(unsigned(out_count_fu_188) + unsigned(ap_const_lv13_42));
    add_ln76_1_fu_652_p2 <= std_logic_vector(unsigned(zext_ln76_fu_648_p1) + unsigned(ap_const_lv8_88));
    add_ln76_fu_642_p2 <= std_logic_vector(unsigned(ptr_reg_432) + unsigned(ap_const_lv7_2));
    add_ln80_fu_705_p2 <= std_logic_vector(unsigned(kr_reg_454) + unsigned(ap_const_lv2_1));
    add_ln82_fu_748_p2 <= std_logic_vector(unsigned(kc_reg_479) + unsigned(ap_const_lv2_1));
    add_ln83_fu_754_p2 <= std_logic_vector(unsigned(zext_ln82_fu_738_p1) + unsigned(ptr_reg_432));
    add_ln94_fu_846_p2 <= std_logic_vector(unsigned(c_1_reg_502) + unsigned(ap_const_lv7_1));
    add_ln95_fu_818_p2 <= std_logic_vector(unsigned(zext_ln95_fu_814_p1) + unsigned(ap_const_lv8_44));
    add_ln96_fu_829_p2 <= std_logic_vector(unsigned(zext_ln95_fu_814_p1) + unsigned(ap_const_lv8_88));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(icmp_ln80_fu_699_p2, ap_block_state10_io, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_predicate_op138_read_state9, in_stream_TVALID_int_regslice)
    begin
        if (((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state10_assign_proc : process(icmp_ln80_fu_699_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state10 <= ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state10_io_assign_proc : process(icmp_ln80_fu_699_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state10_io <= ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state9_assign_proc : process(ap_predicate_op138_read_state9, in_stream_TVALID_int_regslice)
    begin
                ap_block_state9 <= ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln67_fu_605_p2)
    begin
        if (((icmp_ln67_fu_605_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op138_read_state9_assign_proc : process(icmp_ln69_fu_617_p2, tmp_2_fu_629_p3)
    begin
                ap_predicate_op138_read_state9 <= ((tmp_2_fu_629_p3 = ap_const_lv1_0) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln67_fu_605_p2)
    begin
        if (((icmp_ln67_fu_605_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    icmp_ln57_fu_547_p2 <= "1" when (r_fu_172 = ap_const_lv2_3) else "0";
    icmp_ln59_fu_583_p2 <= "1" when (c_reg_421 = ap_const_lv7_44) else "0";
    icmp_ln67_fu_605_p2 <= "1" when (img_r_fu_184 = ap_const_lv7_42) else "0";
    icmp_ln69_fu_617_p2 <= "1" when (ptr_reg_432 = ap_const_lv7_42) else "0";
    icmp_ln80_fu_699_p2 <= "1" when (kr_reg_454 = ap_const_lv2_3) else "0";
    icmp_ln82_fu_742_p2 <= "1" when (kc_reg_479 = ap_const_lv2_3) else "0";
    icmp_ln94_fu_840_p2 <= "1" when (c_1_reg_502 = ap_const_lv7_44) else "0";
    img_r_2_fu_611_p2 <= std_logic_vector(unsigned(img_r_fu_184) + unsigned(ap_const_lv7_1));

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state9, icmp_ln69_fu_617_p2, tmp_2_fu_629_p3, in_stream_TVALID_int_regslice)
    begin
        if (((tmp_2_fu_629_p3 = ap_const_lv1_0) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state9, ap_predicate_op138_read_state9, in_stream_TVALID_int_regslice)
    begin
        if ((not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    kernel_V_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            kernel_V_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            kernel_V_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            kernel_V_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            kernel_V_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_V_address0 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            kernel_V_address0 <= "XXXX";
        end if; 
    end process;


    kernel_V_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state11, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, zext_ln1169_1_fu_733_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            kernel_V_address1 <= zext_ln1169_1_fu_733_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            kernel_V_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            kernel_V_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            kernel_V_address1 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_V_address1 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            kernel_V_address1 <= "XXXX";
        end if; 
    end process;


    kernel_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            kernel_V_ce0 <= ap_const_logic_1;
        else 
            kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    kernel_V_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            kernel_V_ce1 <= ap_const_logic_1;
        else 
            kernel_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    kernel_V_d0_assign_proc : process(ap_CS_fsm_state1, k01, k22_read_reg_873, k21_read_reg_878, k12_read_reg_888, k10_read_reg_898, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            kernel_V_d0 <= k22_read_reg_873;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            kernel_V_d0 <= k21_read_reg_878;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            kernel_V_d0 <= k12_read_reg_888;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            kernel_V_d0 <= k10_read_reg_898;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_V_d0 <= k01;
        else 
            kernel_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    kernel_V_d1_assign_proc : process(ap_CS_fsm_state1, k00, k20_read_reg_883, k11_read_reg_893, k02_read_reg_903, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            kernel_V_d1 <= k20_read_reg_883;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            kernel_V_d1 <= k11_read_reg_893;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            kernel_V_d1 <= k02_read_reg_903;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_V_d1 <= k00;
        else 
            kernel_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    kernel_V_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            kernel_V_we0 <= ap_const_logic_1;
        else 
            kernel_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    kernel_V_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            kernel_V_we1 <= ap_const_logic_1;
        else 
            kernel_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    lhs_1_fu_786_p3 <= (acc_V_3_reg_490 & ap_const_lv16_0);

    linebuf_V_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state17, linebuf_V_addr_3_reg_1046, ap_CS_fsm_state18, zext_ln60_2_fu_578_p1, zext_ln76_1_fu_658_p1, zext_ln1171_3_fu_769_p1, zext_ln96_fu_835_p1, icmp_ln94_fu_840_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            linebuf_V_address0 <= linebuf_V_addr_3_reg_1046;
        elsif (((icmp_ln94_fu_840_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            linebuf_V_address0 <= zext_ln96_fu_835_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            linebuf_V_address0 <= zext_ln1171_3_fu_769_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_V_address0 <= zext_ln76_1_fu_658_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_address0 <= zext_ln60_2_fu_578_p1(8 - 1 downto 0);
        else 
            linebuf_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_V_address1_assign_proc : process(linebuf_V_addr_2_reg_1041, ap_CS_fsm_state17, ap_CS_fsm_state18, zext_ln95_1_fu_824_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            linebuf_V_address1 <= linebuf_V_addr_2_reg_1041;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            linebuf_V_address1 <= zext_ln95_1_fu_824_p1(8 - 1 downto 0);
        else 
            linebuf_V_address1 <= "XXXXXXXX";
        end if; 
    end process;


    linebuf_V_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state7, ap_predicate_op138_read_state9, ap_CS_fsm_state11, ap_CS_fsm_state17, ap_CS_fsm_state18, icmp_ln94_fu_840_p2, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((icmp_ln94_fu_840_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17)))) then 
            linebuf_V_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_ce1_assign_proc : process(ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            linebuf_V_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state7, ap_CS_fsm_state17, linebuf_V_q1, ap_CS_fsm_state18, icmp_ln94_fu_840_p2, in_stream_TDATA_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            linebuf_V_d0 <= linebuf_V_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linebuf_V_d0 <= in_stream_TDATA_int_regslice;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((icmp_ln94_fu_840_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17)))) then 
            linebuf_V_d0 <= ap_const_lv32_0;
        else 
            linebuf_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    linebuf_V_we0_assign_proc : process(ap_CS_fsm_state9, icmp_ln69_fu_617_p2, tmp_2_fu_629_p3, ap_CS_fsm_state7, ap_predicate_op138_read_state9, ap_CS_fsm_state17, icmp_ln59_fu_583_p2, ap_CS_fsm_state18, icmp_ln94_fu_840_p2, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (not(((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op138_read_state9 = ap_const_boolean_1))) and (tmp_2_fu_629_p3 = ap_const_lv1_0) and (icmp_ln69_fu_617_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((icmp_ln94_fu_840_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17)) or ((icmp_ln59_fu_583_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            linebuf_V_we0 <= ap_const_logic_1;
        else 
            linebuf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_we1_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            linebuf_V_we1 <= ap_const_logic_1;
        else 
            linebuf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    out_count_4_fu_718_p2 <= std_logic_vector(unsigned(out_count_1_reg_444) + unsigned(ap_const_lv13_1));

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state10, icmp_ln80_fu_699_p2, ap_CS_fsm_state16, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TLAST_int_regslice <= "1" when (out_count_1_reg_444 = ap_const_lv13_1103) else "0";
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state10, icmp_ln80_fu_699_p2, ap_block_state10_io, out_stream_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state10_io) or ((icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln80_fu_699_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_fu_794_p2 <= std_logic_vector(unsigned(lhs_1_fu_786_p3) + unsigned(r_V_1_reg_1031));
    sub_ln1169_fu_693_p2 <= std_logic_vector(unsigned(tmp_8_fu_675_p3) - unsigned(zext_ln1171_fu_663_p1));
    tmp_1_fu_529_p3 <= (r_fu_172 & ap_const_lv2_0);
    tmp_2_fu_629_p3 <= ptr_reg_432(6 downto 6);
    tmp_7_fu_667_p3 <= (kr_reg_454 & ap_const_lv6_0);
    tmp_8_fu_675_p3 <= (kr_reg_454 & ap_const_lv2_0);
    tmp_fu_521_p3 <= (r_fu_172 & ap_const_lv6_0);
    zext_ln1169_1_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1169_fu_728_p2),64));
    zext_ln1169_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_reg_479),4));
    zext_ln1171_1_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_675_p3),8));
    zext_ln1171_2_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln83_fu_754_p2),8));
    zext_ln1171_3_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1171_1_fu_764_p2),64));
    zext_ln1171_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_reg_454),4));
    zext_ln60_1_fu_569_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_421),8));
    zext_ln60_2_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_1_fu_573_p2),64));
    zext_ln60_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_529_p3),8));
    zext_ln76_1_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_1_fu_652_p2),64));
    zext_ln76_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_642_p2),8));
    zext_ln82_fu_738_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_reg_479),7));
    zext_ln94_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_502),64));
    zext_ln95_1_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_fu_818_p2),64));
    zext_ln95_fu_814_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_502),8));
    zext_ln96_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln96_fu_829_p2),64));
end behav;
