-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_stream_conv2d_stream,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=9981,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=3825,HLS_SYN_LUT=2318,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_44 : STD_LOGIC_VECTOR (6 downto 0) := "1000100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_42 : STD_LOGIC_VECTOR (6 downto 0) := "1000010";
    constant ap_const_lv13_42 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal k00 : STD_LOGIC_VECTOR (31 downto 0);
    signal k01 : STD_LOGIC_VECTOR (31 downto 0);
    signal k02 : STD_LOGIC_VECTOR (31 downto 0);
    signal k10 : STD_LOGIC_VECTOR (31 downto 0);
    signal k11 : STD_LOGIC_VECTOR (31 downto 0);
    signal k12 : STD_LOGIC_VECTOR (31 downto 0);
    signal k20 : STD_LOGIC_VECTOR (31 downto 0);
    signal k21 : STD_LOGIC_VECTOR (31 downto 0);
    signal k22 : STD_LOGIC_VECTOR (31 downto 0);
    signal k22_read_reg_385 : STD_LOGIC_VECTOR (31 downto 0);
    signal k21_read_reg_390 : STD_LOGIC_VECTOR (31 downto 0);
    signal k20_read_reg_395 : STD_LOGIC_VECTOR (31 downto 0);
    signal k12_read_reg_400 : STD_LOGIC_VECTOR (31 downto 0);
    signal k11_read_reg_405 : STD_LOGIC_VECTOR (31 downto 0);
    signal k10_read_reg_410 : STD_LOGIC_VECTOR (31 downto 0);
    signal k02_read_reg_415 : STD_LOGIC_VECTOR (31 downto 0);
    signal k01_read_reg_420 : STD_LOGIC_VECTOR (31 downto 0);
    signal k00_read_reg_425 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_1_reg_430 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln57_fu_304_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln57_reg_437 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln59_fu_333_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal out_count_load_reg_467 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln67_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_V_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal linebuf_V_0_ce0 : STD_LOGIC;
    signal linebuf_V_0_we0 : STD_LOGIC;
    signal linebuf_V_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_ce1 : STD_LOGIC;
    signal linebuf_V_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_ce2 : STD_LOGIC;
    signal linebuf_V_0_q2 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal linebuf_V_1_ce0 : STD_LOGIC;
    signal linebuf_V_1_we0 : STD_LOGIC;
    signal linebuf_V_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal linebuf_V_1_ce1 : STD_LOGIC;
    signal linebuf_V_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_ce2 : STD_LOGIC;
    signal linebuf_V_1_q2 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal linebuf_V_2_ce0 : STD_LOGIC;
    signal linebuf_V_2_we0 : STD_LOGIC;
    signal linebuf_V_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_ce1 : STD_LOGIC;
    signal linebuf_V_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_ce2 : STD_LOGIC;
    signal linebuf_V_2_q2 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_ce3 : STD_LOGIC;
    signal linebuf_V_2_q3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_reg_239 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln57_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln59_fu_320_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_122 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_count_fu_138 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln69_fu_362_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal img_r_fu_142 : STD_LOGIC_VECTOR (6 downto 0);
    signal img_r_2_fu_352_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_count : IN STD_LOGIC_VECTOR (12 downto 0);
        linebuf_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_0_ce0 : OUT STD_LOGIC;
        linebuf_V_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_0_ce1 : OUT STD_LOGIC;
        linebuf_V_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_0_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_0_ce2 : OUT STD_LOGIC;
        linebuf_V_0_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
        k00_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        k01_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        k02_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_1_ce0 : OUT STD_LOGIC;
        linebuf_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_1_ce1 : OUT STD_LOGIC;
        linebuf_V_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_1_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_1_ce2 : OUT STD_LOGIC;
        linebuf_V_1_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
        k10_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        k11_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        k12_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_2_ce0 : OUT STD_LOGIC;
        linebuf_V_2_we0 : OUT STD_LOGIC;
        linebuf_V_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_2_ce1 : OUT STD_LOGIC;
        linebuf_V_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_2_ce2 : OUT STD_LOGIC;
        linebuf_V_2_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_address3 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_2_ce3 : OUT STD_LOGIC;
        linebuf_V_2_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
        k20_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        k21_cast : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln67 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_shift_up IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        linebuf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_1_ce0 : OUT STD_LOGIC;
        linebuf_V_1_we0 : OUT STD_LOGIC;
        linebuf_V_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_1_ce1 : OUT STD_LOGIC;
        linebuf_V_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_0_ce0 : OUT STD_LOGIC;
        linebuf_V_0_we0 : OUT STD_LOGIC;
        linebuf_V_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        linebuf_V_2_ce0 : OUT STD_LOGIC;
        linebuf_V_2_we0 : OUT STD_LOGIC;
        linebuf_V_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        linebuf_V_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_linebuf_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_linebuf_V_2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address3 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        k00 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k01 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k02 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k20 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k21 : OUT STD_LOGIC_VECTOR (31 downto 0);
        k22 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    linebuf_V_0_U : component conv2d_stream_linebuf_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 68,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => linebuf_V_0_address0,
        ce0 => linebuf_V_0_ce0,
        we0 => linebuf_V_0_we0,
        d0 => linebuf_V_0_d0,
        q0 => linebuf_V_0_q0,
        address1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1,
        ce1 => linebuf_V_0_ce1,
        q1 => linebuf_V_0_q1,
        address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2,
        ce2 => linebuf_V_0_ce2,
        q2 => linebuf_V_0_q2);

    linebuf_V_1_U : component conv2d_stream_linebuf_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 68,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => linebuf_V_1_address0,
        ce0 => linebuf_V_1_ce0,
        we0 => linebuf_V_1_we0,
        d0 => linebuf_V_1_d0,
        q0 => linebuf_V_1_q0,
        address1 => linebuf_V_1_address1,
        ce1 => linebuf_V_1_ce1,
        q1 => linebuf_V_1_q1,
        address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2,
        ce2 => linebuf_V_1_ce2,
        q2 => linebuf_V_1_q2);

    linebuf_V_2_U : component conv2d_stream_linebuf_V_2
    generic map (
        DataWidth => 32,
        AddressRange => 68,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => linebuf_V_2_address0,
        ce0 => linebuf_V_2_ce0,
        we0 => linebuf_V_2_we0,
        d0 => linebuf_V_2_d0,
        q0 => linebuf_V_2_q0,
        address1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1,
        ce1 => linebuf_V_2_ce1,
        q1 => linebuf_V_2_q1,
        address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2,
        ce2 => linebuf_V_2_ce2,
        q2 => linebuf_V_2_q2,
        address3 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3,
        ce3 => linebuf_V_2_ce3,
        q3 => linebuf_V_2_q3);

    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250 : component conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY,
        out_count => out_count_load_reg_467,
        linebuf_V_0_address0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0,
        linebuf_V_0_ce0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0,
        linebuf_V_0_q0 => linebuf_V_0_q0,
        linebuf_V_0_address1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1,
        linebuf_V_0_ce1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1,
        linebuf_V_0_q1 => linebuf_V_0_q1,
        linebuf_V_0_address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2,
        linebuf_V_0_ce2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2,
        linebuf_V_0_q2 => linebuf_V_0_q2,
        k00_cast => k00_read_reg_425,
        k01_cast => k01_read_reg_420,
        k02_cast => k02_read_reg_415,
        linebuf_V_1_address0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0,
        linebuf_V_1_ce0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0,
        linebuf_V_1_q0 => linebuf_V_1_q0,
        linebuf_V_1_address1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1,
        linebuf_V_1_ce1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1,
        linebuf_V_1_q1 => linebuf_V_1_q1,
        linebuf_V_1_address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2,
        linebuf_V_1_ce2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2,
        linebuf_V_1_q2 => linebuf_V_1_q2,
        k10_cast => k10_read_reg_410,
        k11_cast => k11_read_reg_405,
        k12_cast => k12_read_reg_400,
        linebuf_V_2_address0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0,
        linebuf_V_2_ce0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0,
        linebuf_V_2_we0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0,
        linebuf_V_2_d0 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0,
        linebuf_V_2_address1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1,
        linebuf_V_2_ce1 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1,
        linebuf_V_2_q1 => linebuf_V_2_q1,
        linebuf_V_2_address2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2,
        linebuf_V_2_ce2 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2,
        linebuf_V_2_q2 => linebuf_V_2_q2,
        linebuf_V_2_address3 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3,
        linebuf_V_2_ce3 => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3,
        linebuf_V_2_q3 => linebuf_V_2_q3,
        k20_cast => k20_read_reg_395,
        k21_cast => k21_read_reg_390,
        sext_ln67 => k22_read_reg_385,
        out_stream_TDATA => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID,
        out_stream_TKEEP => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB,
        out_stream_TLAST => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice);

    grp_conv2d_stream_Pipeline_shift_up_fu_283 : component conv2d_stream_conv2d_stream_Pipeline_shift_up
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready,
        linebuf_V_1_address0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0,
        linebuf_V_1_ce0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0,
        linebuf_V_1_we0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0,
        linebuf_V_1_d0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0,
        linebuf_V_1_address1 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1,
        linebuf_V_1_ce1 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1,
        linebuf_V_1_q1 => linebuf_V_1_q1,
        linebuf_V_0_address0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0,
        linebuf_V_0_ce0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0,
        linebuf_V_0_we0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0,
        linebuf_V_0_d0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0,
        linebuf_V_2_address0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0,
        linebuf_V_2_ce0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0,
        linebuf_V_2_we0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0,
        linebuf_V_2_d0 => grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0,
        linebuf_V_2_q0 => linebuf_V_2_q0);

    CTRL_s_axi_U : component conv2d_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        k00 => k00,
        k01 => k01,
        k02 => k02,
        k10 => k10,
        k11 => k11,
        k12 => k12,
        k20 => k20,
        k21 => k21,
        k22 => k22,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_in_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA,
        vld_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP,
        vld_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB,
        vld_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST,
        vld_in => grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln67_fu_346_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln59_fu_327_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                c_reg_239 <= add_ln59_fu_333_p2;
            elsif (((icmp_ln57_fu_298_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_reg_239 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    img_r_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln57_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                img_r_fu_142 <= ap_const_lv7_0;
            elsif (((icmp_ln67_fu_346_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                img_r_fu_142 <= img_r_2_fu_352_p2;
            end if; 
        end if;
    end process;

    out_count_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln57_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                out_count_fu_138 <= ap_const_lv13_0;
            elsif (((icmp_ln67_fu_346_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_count_fu_138 <= add_ln69_fu_362_p2;
            end if; 
        end if;
    end process;

    r_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_fu_122 <= ap_const_lv2_0;
            elsif (((icmp_ln59_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                r_fu_122 <= add_ln57_reg_437;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln57_reg_437 <= add_ln57_fu_304_p2;
                r_1_reg_430 <= r_fu_122;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                k00_read_reg_425 <= k00;
                k01_read_reg_420 <= k01;
                k02_read_reg_415 <= k02;
                k10_read_reg_410 <= k10;
                k11_read_reg_405 <= k11;
                k12_read_reg_400 <= k12;
                k20_read_reg_395 <= k20;
                k21_read_reg_390 <= k21;
                k22_read_reg_385 <= k22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln67_fu_346_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                out_count_load_reg_467 <= out_count_fu_138;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln67_fu_346_p2, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done, grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done, icmp_ln57_fu_298_p2, icmp_ln59_fu_327_p2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln57_fu_298_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln59_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln67_fu_346_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln57_fu_304_p2 <= std_logic_vector(unsigned(r_fu_122) + unsigned(ap_const_lv2_1));
    add_ln59_fu_333_p2 <= std_logic_vector(unsigned(c_reg_239) + unsigned(ap_const_lv7_1));
    add_ln69_fu_362_p2 <= std_logic_vector(unsigned(out_count_fu_138) + unsigned(ap_const_lv13_42));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done)
    begin
        if ((grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done)
    begin
        if ((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg;
    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state5);
    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start <= grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg;
    icmp_ln57_fu_298_p2 <= "1" when (r_fu_122 = ap_const_lv2_3) else "0";
    icmp_ln59_fu_327_p2 <= "1" when (c_reg_239 = ap_const_lv7_44) else "0";
    icmp_ln67_fu_346_p2 <= "1" when (img_r_fu_142 = ap_const_lv7_42) else "0";
    img_r_2_fu_352_p2 <= std_logic_vector(unsigned(img_r_fu_142) + unsigned(ap_const_lv7_1));
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_address0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0, ap_CS_fsm_state5, ap_CS_fsm_state7, zext_ln59_fu_320_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_0_address0 <= zext_ln59_fu_320_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_0_address0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_0_address0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0;
        else 
            linebuf_V_0_address0 <= "XXXXXXX";
        end if; 
    end process;


    linebuf_V_0_ce0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_0_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_0_ce0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_0_ce0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0;
        else 
            linebuf_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_0_ce1 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1;
        else 
            linebuf_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce2_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_0_ce2 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2;
        else 
            linebuf_V_0_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_d0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_0_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_0_d0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0;
        else 
            linebuf_V_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    linebuf_V_0_we0_assign_proc : process(r_1_reg_430, ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0, icmp_ln59_fu_327_p2, ap_CS_fsm_state7)
    begin
        if (((r_1_reg_430 = ap_const_lv2_0) and (icmp_ln59_fu_327_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            linebuf_V_0_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_0_we0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0;
        else 
            linebuf_V_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_address0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0, ap_CS_fsm_state5, ap_CS_fsm_state7, zext_ln59_fu_320_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_1_address0 <= zext_ln59_fu_320_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_address0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_1_address0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0;
        else 
            linebuf_V_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    linebuf_V_1_address1_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_address1 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_1_address1 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1;
        else 
            linebuf_V_1_address1 <= "XXXXXXX";
        end if; 
    end process;


    linebuf_V_1_ce0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_ce0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_1_ce0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0;
        else 
            linebuf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_ce1 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_1_ce1 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1;
        else 
            linebuf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce2_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_1_ce2 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2;
        else 
            linebuf_V_1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_d0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_1_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_d0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0;
        else 
            linebuf_V_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    linebuf_V_1_we0_assign_proc : process(r_1_reg_430, ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0, icmp_ln59_fu_327_p2, ap_CS_fsm_state7)
    begin
        if (((r_1_reg_430 = ap_const_lv2_1) and (icmp_ln59_fu_327_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            linebuf_V_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_1_we0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0;
        else 
            linebuf_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_address0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0, ap_CS_fsm_state5, ap_CS_fsm_state7, zext_ln59_fu_320_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_2_address0 <= zext_ln59_fu_320_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_2_address0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_address0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0;
        else 
            linebuf_V_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    linebuf_V_2_ce0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_2_ce0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_ce0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0;
        else 
            linebuf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_ce1 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1;
        else 
            linebuf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce2_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_ce2 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2;
        else 
            linebuf_V_2_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce3_assign_proc : process(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_ce3 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3;
        else 
            linebuf_V_2_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_d0_assign_proc : process(ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            linebuf_V_2_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_2_d0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_d0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0;
        else 
            linebuf_V_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    linebuf_V_2_we0_assign_proc : process(r_1_reg_430, ap_CS_fsm_state3, grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0, grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0, icmp_ln59_fu_327_p2, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((not((r_1_reg_430 = ap_const_lv2_0)) and not((r_1_reg_430 = ap_const_lv2_1)) and (icmp_ln59_fu_327_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            linebuf_V_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            linebuf_V_2_we0 <= grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            linebuf_V_2_we0 <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0;
        else 
            linebuf_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID;
    zext_ln59_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_239),64));
end behav;
