// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        out_count,
        linebuf_V_0_address0,
        linebuf_V_0_ce0,
        linebuf_V_0_q0,
        linebuf_V_0_address1,
        linebuf_V_0_ce1,
        linebuf_V_0_q1,
        linebuf_V_0_address2,
        linebuf_V_0_ce2,
        linebuf_V_0_q2,
        k00_cast,
        k01_cast,
        k02_cast,
        linebuf_V_1_address0,
        linebuf_V_1_ce0,
        linebuf_V_1_q0,
        linebuf_V_1_address1,
        linebuf_V_1_ce1,
        linebuf_V_1_q1,
        linebuf_V_1_address2,
        linebuf_V_1_ce2,
        linebuf_V_1_q2,
        k10_cast,
        k11_cast,
        k12_cast,
        linebuf_V_2_address0,
        linebuf_V_2_ce0,
        linebuf_V_2_we0,
        linebuf_V_2_d0,
        linebuf_V_2_address1,
        linebuf_V_2_ce1,
        linebuf_V_2_q1,
        linebuf_V_2_address2,
        linebuf_V_2_ce2,
        linebuf_V_2_q2,
        linebuf_V_2_address3,
        linebuf_V_2_ce3,
        linebuf_V_2_q3,
        k20_cast,
        k21_cast,
        sext_ln67,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [12:0] out_count;
output  [6:0] linebuf_V_0_address0;
output   linebuf_V_0_ce0;
input  [31:0] linebuf_V_0_q0;
output  [6:0] linebuf_V_0_address1;
output   linebuf_V_0_ce1;
input  [31:0] linebuf_V_0_q1;
output  [6:0] linebuf_V_0_address2;
output   linebuf_V_0_ce2;
input  [31:0] linebuf_V_0_q2;
input  [31:0] k00_cast;
input  [31:0] k01_cast;
input  [31:0] k02_cast;
output  [6:0] linebuf_V_1_address0;
output   linebuf_V_1_ce0;
input  [31:0] linebuf_V_1_q0;
output  [6:0] linebuf_V_1_address1;
output   linebuf_V_1_ce1;
input  [31:0] linebuf_V_1_q1;
output  [6:0] linebuf_V_1_address2;
output   linebuf_V_1_ce2;
input  [31:0] linebuf_V_1_q2;
input  [31:0] k10_cast;
input  [31:0] k11_cast;
input  [31:0] k12_cast;
output  [6:0] linebuf_V_2_address0;
output   linebuf_V_2_ce0;
output   linebuf_V_2_we0;
output  [31:0] linebuf_V_2_d0;
output  [6:0] linebuf_V_2_address1;
output   linebuf_V_2_ce1;
input  [31:0] linebuf_V_2_q1;
output  [6:0] linebuf_V_2_address2;
output   linebuf_V_2_ce2;
input  [31:0] linebuf_V_2_q2;
output  [6:0] linebuf_V_2_address3;
output   linebuf_V_2_ce3;
input  [31:0] linebuf_V_2_q3;
input  [31:0] k20_cast;
input  [31:0] k21_cast;
input  [31:0] sext_ln67;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;

reg ap_idle;
reg linebuf_V_0_ce0;
reg linebuf_V_0_ce1;
reg linebuf_V_0_ce2;
reg linebuf_V_1_ce0;
reg linebuf_V_1_ce1;
reg linebuf_V_1_ce2;
reg linebuf_V_2_ce0;
reg linebuf_V_2_we0;
reg linebuf_V_2_ce1;
reg linebuf_V_2_ce2;
reg linebuf_V_2_ce3;
reg out_stream_TVALID;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln69_fu_372_p2;
wire   [0:0] tmp_1_fu_391_p3;
reg    ap_predicate_op47_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    in_stream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire  signed [47:0] sext_ln67_cast_fu_323_p1;
reg  signed [47:0] sext_ln67_cast_reg_737;
wire  signed [47:0] k21_cast_cast_fu_327_p1;
reg  signed [47:0] k21_cast_cast_reg_742;
wire  signed [47:0] k20_cast_cast_fu_331_p1;
reg  signed [47:0] k20_cast_cast_reg_747;
wire  signed [47:0] k12_cast_cast_fu_335_p1;
reg  signed [47:0] k12_cast_cast_reg_752;
wire  signed [47:0] k11_cast_cast_fu_339_p1;
reg  signed [47:0] k11_cast_cast_reg_757;
wire  signed [47:0] k10_cast_cast_fu_343_p1;
reg  signed [47:0] k10_cast_cast_reg_762;
wire  signed [47:0] k02_cast_cast_fu_347_p1;
reg  signed [47:0] k02_cast_cast_reg_767;
wire  signed [47:0] k01_cast_cast_fu_351_p1;
reg  signed [47:0] k01_cast_cast_reg_772;
wire  signed [47:0] k00_cast_cast_fu_355_p1;
reg  signed [47:0] k00_cast_cast_reg_777;
wire   [63:0] zext_ln1168_1_fu_428_p1;
reg   [63:0] zext_ln1168_1_reg_799;
reg  signed [31:0] linebuf_V_0_load_reg_834;
reg  signed [31:0] linebuf_V_0_load_1_reg_839;
reg  signed [31:0] linebuf_V_0_load_2_reg_844;
reg   [31:0] linebuf_V_1_load_reg_849;
reg  signed [31:0] linebuf_V_1_load_reg_849_pp0_iter2_reg;
reg   [31:0] linebuf_V_1_load_1_reg_854;
reg  signed [31:0] linebuf_V_1_load_1_reg_854_pp0_iter2_reg;
reg   [31:0] linebuf_V_1_load_2_reg_859;
reg   [31:0] linebuf_V_1_load_2_reg_859_pp0_iter2_reg;
reg  signed [31:0] linebuf_V_1_load_2_reg_859_pp0_iter3_reg;
reg   [31:0] linebuf_V_2_load_reg_864;
reg   [31:0] linebuf_V_2_load_reg_864_pp0_iter2_reg;
reg  signed [31:0] linebuf_V_2_load_reg_864_pp0_iter3_reg;
reg   [31:0] linebuf_V_2_load_1_reg_869;
reg   [31:0] linebuf_V_2_load_1_reg_869_pp0_iter2_reg;
reg   [31:0] linebuf_V_2_load_1_reg_869_pp0_iter3_reg;
reg  signed [31:0] linebuf_V_2_load_1_reg_869_pp0_iter4_reg;
reg   [31:0] linebuf_V_2_load_2_reg_894;
reg   [31:0] linebuf_V_2_load_2_reg_894_pp0_iter3_reg;
reg  signed [31:0] linebuf_V_2_load_2_reg_894_pp0_iter4_reg;
wire   [47:0] grp_fu_450_p2;
reg   [47:0] r_V_1_reg_899;
reg   [31:0] tmp_reg_904;
wire   [47:0] grp_fu_458_p2;
reg   [47:0] r_V_2_reg_909;
wire   [47:0] grp_fu_476_p2;
reg   [47:0] r_V_3_reg_924;
reg   [31:0] tmp_5_reg_929;
wire   [47:0] grp_fu_484_p2;
reg   [47:0] r_V_4_reg_934;
wire   [47:0] grp_fu_537_p2;
reg   [47:0] r_V_5_reg_949;
reg   [31:0] tmp_7_reg_954;
wire   [47:0] grp_fu_545_p2;
reg   [47:0] r_V_6_reg_959;
wire   [47:0] grp_fu_598_p2;
reg   [47:0] r_V_7_reg_974;
reg   [31:0] tmp_9_reg_979;
wire   [47:0] grp_fu_606_p2;
reg   [47:0] r_V_8_reg_984;
wire   [63:0] zext_ln76_fu_410_p1;
wire   [63:0] zext_ln69_fu_384_p1;
wire   [63:0] zext_ln1168_fu_415_p1;
reg   [12:0] out_count_1_fu_102;
wire   [12:0] out_count_2_fu_712_p2;
wire    ap_loop_init;
reg   [6:0] ptr_fu_106;
reg   [6:0] ap_sig_allocacmp_ptr_1;
wire   [6:0] add_ln83_fu_378_p2;
reg    ap_block_pp0_stage0_01001;
wire   [6:0] add_ln76_fu_404_p2;
wire   [6:0] add_ln83_1_fu_422_p2;
wire  signed [31:0] grp_fu_442_p1;
wire  signed [31:0] grp_fu_450_p1;
wire  signed [31:0] grp_fu_458_p1;
wire   [47:0] grp_fu_442_p2;
wire  signed [31:0] grp_fu_476_p1;
wire  signed [31:0] grp_fu_484_p1;
wire   [47:0] lhs_fu_489_p3;
wire   [47:0] ret_V_fu_496_p2;
wire   [31:0] tmp_4_fu_501_p4;
wire   [47:0] lhs_1_fu_511_p3;
wire   [47:0] ret_V_1_fu_519_p2;
wire  signed [31:0] grp_fu_537_p1;
wire  signed [31:0] grp_fu_545_p1;
wire   [47:0] lhs_2_fu_550_p3;
wire   [47:0] ret_V_2_fu_557_p2;
wire   [31:0] tmp_6_fu_562_p4;
wire   [47:0] lhs_3_fu_572_p3;
wire   [47:0] ret_V_3_fu_580_p2;
wire  signed [31:0] grp_fu_598_p1;
wire  signed [31:0] grp_fu_606_p1;
wire   [47:0] lhs_4_fu_611_p3;
wire   [47:0] ret_V_4_fu_618_p2;
wire   [31:0] tmp_8_fu_623_p4;
wire   [47:0] lhs_5_fu_633_p3;
wire   [47:0] ret_V_5_fu_641_p2;
wire   [47:0] lhs_6_fu_659_p3;
wire   [47:0] ret_V_6_fu_666_p2;
wire   [31:0] tmp_s_fu_671_p4;
wire   [47:0] lhs_7_fu_681_p3;
wire   [47:0] ret_V_7_fu_689_p2;
reg    grp_fu_442_ce;
reg    grp_fu_450_ce;
reg    grp_fu_458_ce;
reg    grp_fu_476_ce;
reg    grp_fu_484_ce;
reg    grp_fu_537_ce;
reg    grp_fu_545_ce;
reg    grp_fu_598_ce;
reg    grp_fu_606_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_reg_834),
    .din1(grp_fu_442_p1),
    .ce(grp_fu_442_ce),
    .dout(grp_fu_442_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_1_reg_839),
    .din1(grp_fu_450_p1),
    .ce(grp_fu_450_ce),
    .dout(grp_fu_450_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_2_reg_844),
    .din1(grp_fu_458_p1),
    .ce(grp_fu_458_ce),
    .dout(grp_fu_458_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_reg_849_pp0_iter2_reg),
    .din1(grp_fu_476_p1),
    .ce(grp_fu_476_ce),
    .dout(grp_fu_476_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_1_reg_854_pp0_iter2_reg),
    .din1(grp_fu_484_p1),
    .ce(grp_fu_484_ce),
    .dout(grp_fu_484_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_2_reg_859_pp0_iter3_reg),
    .din1(grp_fu_537_p1),
    .ce(grp_fu_537_ce),
    .dout(grp_fu_537_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_reg_864_pp0_iter3_reg),
    .din1(grp_fu_545_p1),
    .ce(grp_fu_545_ce),
    .dout(grp_fu_545_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_1_reg_869_pp0_iter4_reg),
    .din1(grp_fu_598_p1),
    .ce(grp_fu_598_ce),
    .dout(grp_fu_598_p2)
);

conv2d_stream_mul_32s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_2_reg_894_pp0_iter4_reg),
    .din1(grp_fu_606_p1),
    .ce(grp_fu_606_ce),
    .dout(grp_fu_606_p2)
);

conv2d_stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_count_1_fu_102 <= out_count;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            out_count_1_fu_102 <= out_count_2_fu_712_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_372_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            ptr_fu_106 <= add_ln83_fu_378_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ptr_fu_106 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        k00_cast_cast_reg_777 <= k00_cast_cast_fu_355_p1;
        k01_cast_cast_reg_772 <= k01_cast_cast_fu_351_p1;
        k02_cast_cast_reg_767 <= k02_cast_cast_fu_347_p1;
        k10_cast_cast_reg_762 <= k10_cast_cast_fu_343_p1;
        k11_cast_cast_reg_757 <= k11_cast_cast_fu_339_p1;
        k12_cast_cast_reg_752 <= k12_cast_cast_fu_335_p1;
        k20_cast_cast_reg_747 <= k20_cast_cast_fu_331_p1;
        k21_cast_cast_reg_742 <= k21_cast_cast_fu_327_p1;
        sext_ln67_cast_reg_737 <= sext_ln67_cast_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        linebuf_V_1_load_1_reg_854_pp0_iter2_reg <= linebuf_V_1_load_1_reg_854;
        linebuf_V_1_load_2_reg_859_pp0_iter2_reg <= linebuf_V_1_load_2_reg_859;
        linebuf_V_1_load_2_reg_859_pp0_iter3_reg <= linebuf_V_1_load_2_reg_859_pp0_iter2_reg;
        linebuf_V_1_load_reg_849_pp0_iter2_reg <= linebuf_V_1_load_reg_849;
        linebuf_V_2_load_1_reg_869_pp0_iter2_reg <= linebuf_V_2_load_1_reg_869;
        linebuf_V_2_load_1_reg_869_pp0_iter3_reg <= linebuf_V_2_load_1_reg_869_pp0_iter2_reg;
        linebuf_V_2_load_1_reg_869_pp0_iter4_reg <= linebuf_V_2_load_1_reg_869_pp0_iter3_reg;
        linebuf_V_2_load_2_reg_894_pp0_iter3_reg <= linebuf_V_2_load_2_reg_894;
        linebuf_V_2_load_2_reg_894_pp0_iter4_reg <= linebuf_V_2_load_2_reg_894_pp0_iter3_reg;
        linebuf_V_2_load_reg_864_pp0_iter2_reg <= linebuf_V_2_load_reg_864;
        linebuf_V_2_load_reg_864_pp0_iter3_reg <= linebuf_V_2_load_reg_864_pp0_iter2_reg;
        r_V_1_reg_899 <= grp_fu_450_p2;
        r_V_2_reg_909 <= grp_fu_458_p2;
        r_V_3_reg_924 <= grp_fu_476_p2;
        r_V_4_reg_934 <= grp_fu_484_p2;
        r_V_5_reg_949 <= grp_fu_537_p2;
        r_V_6_reg_959 <= grp_fu_545_p2;
        r_V_7_reg_974 <= grp_fu_598_p2;
        r_V_8_reg_984 <= grp_fu_606_p2;
        tmp_5_reg_929 <= {{ret_V_1_fu_519_p2[47:16]}};
        tmp_7_reg_954 <= {{ret_V_3_fu_580_p2[47:16]}};
        tmp_9_reg_979 <= {{ret_V_5_fu_641_p2[47:16]}};
        tmp_reg_904 <= {{grp_fu_442_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_load_1_reg_839 <= linebuf_V_0_q1;
        linebuf_V_0_load_2_reg_844 <= linebuf_V_0_q0;
        linebuf_V_0_load_reg_834 <= linebuf_V_0_q2;
        linebuf_V_1_load_1_reg_854 <= linebuf_V_1_q1;
        linebuf_V_1_load_2_reg_859 <= linebuf_V_1_q0;
        linebuf_V_1_load_reg_849 <= linebuf_V_1_q2;
        linebuf_V_2_load_1_reg_869 <= linebuf_V_2_q2;
        linebuf_V_2_load_reg_864 <= linebuf_V_2_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf_V_2_load_2_reg_894 <= linebuf_V_2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln1168_1_reg_799[6 : 0] <= zext_ln1168_1_fu_428_p1[6 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln69_fu_372_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ptr_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_ptr_1 = ptr_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_442_ce = 1'b1;
    end else begin
        grp_fu_442_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_450_ce = 1'b1;
    end else begin
        grp_fu_450_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_458_ce = 1'b1;
    end else begin
        grp_fu_458_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_476_ce = 1'b1;
    end else begin
        grp_fu_476_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_484_ce = 1'b1;
    end else begin
        grp_fu_484_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_537_ce = 1'b1;
    end else begin
        grp_fu_537_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_545_ce = 1'b1;
    end else begin
        grp_fu_545_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_598_ce = 1'b1;
    end else begin
        grp_fu_598_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_606_ce = 1'b1;
    end else begin
        grp_fu_606_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op47_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op47_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce0 = 1'b1;
    end else begin
        linebuf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce1 = 1'b1;
    end else begin
        linebuf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce2 = 1'b1;
    end else begin
        linebuf_V_0_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce0 = 1'b1;
    end else begin
        linebuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce1 = 1'b1;
    end else begin
        linebuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce2 = 1'b1;
    end else begin
        linebuf_V_1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce0 = 1'b1;
    end else begin
        linebuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce1 = 1'b1;
    end else begin
        linebuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce2 = 1'b1;
    end else begin
        linebuf_V_2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce3 = 1'b1;
    end else begin
        linebuf_V_2_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_fu_391_p3 == 1'd0) & (icmp_ln69_fu_372_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_we0 = 1'b1;
    end else begin
        linebuf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln76_fu_404_p2 = (ap_sig_allocacmp_ptr_1 + 7'd2);

assign add_ln83_1_fu_422_p2 = (ap_sig_allocacmp_ptr_1 + 7'd2);

assign add_ln83_fu_378_p2 = (ap_sig_allocacmp_ptr_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op47_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op47_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op47_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op47_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (out_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op47_read_state1 = ((tmp_1_fu_391_p3 == 1'd0) & (icmp_ln69_fu_372_p2 == 1'd0));
end

assign grp_fu_442_p1 = k00_cast_cast_reg_777;

assign grp_fu_450_p1 = k01_cast_cast_reg_772;

assign grp_fu_458_p1 = k02_cast_cast_reg_767;

assign grp_fu_476_p1 = k10_cast_cast_reg_762;

assign grp_fu_484_p1 = k11_cast_cast_reg_757;

assign grp_fu_537_p1 = k12_cast_cast_reg_752;

assign grp_fu_545_p1 = k20_cast_cast_reg_747;

assign grp_fu_598_p1 = k21_cast_cast_reg_742;

assign grp_fu_606_p1 = sext_ln67_cast_reg_737;

assign icmp_ln69_fu_372_p2 = ((ap_sig_allocacmp_ptr_1 == 7'd66) ? 1'b1 : 1'b0);

assign k00_cast_cast_fu_355_p1 = $signed(k00_cast);

assign k01_cast_cast_fu_351_p1 = $signed(k01_cast);

assign k02_cast_cast_fu_347_p1 = $signed(k02_cast);

assign k10_cast_cast_fu_343_p1 = $signed(k10_cast);

assign k11_cast_cast_fu_339_p1 = $signed(k11_cast);

assign k12_cast_cast_fu_335_p1 = $signed(k12_cast);

assign k20_cast_cast_fu_331_p1 = $signed(k20_cast);

assign k21_cast_cast_fu_327_p1 = $signed(k21_cast);

assign lhs_1_fu_511_p3 = {{tmp_4_fu_501_p4}, {16'd0}};

assign lhs_2_fu_550_p3 = {{tmp_5_reg_929}, {16'd0}};

assign lhs_3_fu_572_p3 = {{tmp_6_fu_562_p4}, {16'd0}};

assign lhs_4_fu_611_p3 = {{tmp_7_reg_954}, {16'd0}};

assign lhs_5_fu_633_p3 = {{tmp_8_fu_623_p4}, {16'd0}};

assign lhs_6_fu_659_p3 = {{tmp_9_reg_979}, {16'd0}};

assign lhs_7_fu_681_p3 = {{tmp_s_fu_671_p4}, {16'd0}};

assign lhs_fu_489_p3 = {{tmp_reg_904}, {16'd0}};

assign linebuf_V_0_address0 = zext_ln1168_1_fu_428_p1;

assign linebuf_V_0_address1 = zext_ln1168_fu_415_p1;

assign linebuf_V_0_address2 = zext_ln69_fu_384_p1;

assign linebuf_V_1_address0 = zext_ln1168_1_fu_428_p1;

assign linebuf_V_1_address1 = zext_ln1168_fu_415_p1;

assign linebuf_V_1_address2 = zext_ln69_fu_384_p1;

assign linebuf_V_2_address0 = zext_ln76_fu_410_p1;

assign linebuf_V_2_address1 = zext_ln1168_1_reg_799;

assign linebuf_V_2_address2 = zext_ln1168_fu_415_p1;

assign linebuf_V_2_address3 = zext_ln69_fu_384_p1;

assign linebuf_V_2_d0 = in_stream_TDATA;

assign out_count_2_fu_712_p2 = (out_count_1_fu_102 + 13'd1);

assign out_stream_TDATA = {{ret_V_7_fu_689_p2[47:16]}};

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = ((out_count_1_fu_102 == 13'd4355) ? 1'b1 : 1'b0);

assign out_stream_TSTRB = 4'd15;

assign ret_V_1_fu_519_p2 = (lhs_1_fu_511_p3 + r_V_2_reg_909);

assign ret_V_2_fu_557_p2 = (lhs_2_fu_550_p3 + r_V_3_reg_924);

assign ret_V_3_fu_580_p2 = (lhs_3_fu_572_p3 + r_V_4_reg_934);

assign ret_V_4_fu_618_p2 = (lhs_4_fu_611_p3 + r_V_5_reg_949);

assign ret_V_5_fu_641_p2 = (lhs_5_fu_633_p3 + r_V_6_reg_959);

assign ret_V_6_fu_666_p2 = (lhs_6_fu_659_p3 + r_V_7_reg_974);

assign ret_V_7_fu_689_p2 = (lhs_7_fu_681_p3 + r_V_8_reg_984);

assign ret_V_fu_496_p2 = (lhs_fu_489_p3 + r_V_1_reg_899);

assign sext_ln67_cast_fu_323_p1 = $signed(sext_ln67);

assign tmp_1_fu_391_p3 = ap_sig_allocacmp_ptr_1[32'd6];

assign tmp_4_fu_501_p4 = {{ret_V_fu_496_p2[47:16]}};

assign tmp_6_fu_562_p4 = {{ret_V_2_fu_557_p2[47:16]}};

assign tmp_8_fu_623_p4 = {{ret_V_4_fu_618_p2[47:16]}};

assign tmp_s_fu_671_p4 = {{ret_V_6_fu_666_p2[47:16]}};

assign zext_ln1168_1_fu_428_p1 = add_ln83_1_fu_422_p2;

assign zext_ln1168_fu_415_p1 = add_ln83_fu_378_p2;

assign zext_ln69_fu_384_p1 = ap_sig_allocacmp_ptr_1;

assign zext_ln76_fu_410_p1 = add_ln76_fu_404_p2;

always @ (posedge ap_clk) begin
    zext_ln1168_1_reg_799[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right
