-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_count : IN STD_LOGIC_VECTOR (12 downto 0);
    linebuf_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce0 : OUT STD_LOGIC;
    linebuf_V_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce1 : OUT STD_LOGIC;
    linebuf_V_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_0_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce2 : OUT STD_LOGIC;
    linebuf_V_0_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    k00_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    k01_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    k02_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce0 : OUT STD_LOGIC;
    linebuf_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce1 : OUT STD_LOGIC;
    linebuf_V_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce2 : OUT STD_LOGIC;
    linebuf_V_1_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    k10_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    k11_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    k12_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce0 : OUT STD_LOGIC;
    linebuf_V_2_we0 : OUT STD_LOGIC;
    linebuf_V_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce1 : OUT STD_LOGIC;
    linebuf_V_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce2 : OUT STD_LOGIC;
    linebuf_V_2_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address3 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce3 : OUT STD_LOGIC;
    linebuf_V_2_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    k20_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    k21_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln67 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_42 : STD_LOGIC_VECTOR (6 downto 0) := "1000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv13_1103 : STD_LOGIC_VECTOR (12 downto 0) := "1000100000011";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln69_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op47_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln67_cast_fu_323_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln67_cast_reg_737 : STD_LOGIC_VECTOR (47 downto 0);
    signal k21_cast_cast_fu_327_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k21_cast_cast_reg_742 : STD_LOGIC_VECTOR (47 downto 0);
    signal k20_cast_cast_fu_331_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k20_cast_cast_reg_747 : STD_LOGIC_VECTOR (47 downto 0);
    signal k12_cast_cast_fu_335_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k12_cast_cast_reg_752 : STD_LOGIC_VECTOR (47 downto 0);
    signal k11_cast_cast_fu_339_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k11_cast_cast_reg_757 : STD_LOGIC_VECTOR (47 downto 0);
    signal k10_cast_cast_fu_343_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k10_cast_cast_reg_762 : STD_LOGIC_VECTOR (47 downto 0);
    signal k02_cast_cast_fu_347_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k02_cast_cast_reg_767 : STD_LOGIC_VECTOR (47 downto 0);
    signal k01_cast_cast_fu_351_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k01_cast_cast_reg_772 : STD_LOGIC_VECTOR (47 downto 0);
    signal k00_cast_cast_fu_355_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k00_cast_cast_reg_777 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln1168_1_fu_428_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1168_1_reg_799 : STD_LOGIC_VECTOR (63 downto 0);
    signal linebuf_V_0_load_reg_834 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_load_1_reg_839 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_load_2_reg_844 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_reg_849 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_reg_849_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_1_reg_854 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_1_reg_854_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_2_reg_859 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_2_reg_859_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_2_reg_859_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_reg_864 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_reg_864_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_reg_864_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_1_reg_869 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_1_reg_869_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_1_reg_869_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_1_reg_869_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_2_reg_894 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_2_reg_894_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_2_reg_894_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_450_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_1_reg_899 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_reg_904 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_458_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_2_reg_909 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_476_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_3_reg_924 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_5_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_484_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_4_reg_934 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_537_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_5_reg_949 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_7_reg_954 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_545_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_6_reg_959 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_598_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_7_reg_974 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_9_reg_979 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_606_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_8_reg_984 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln76_fu_410_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_fu_384_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1168_fu_415_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_count_1_fu_102 : STD_LOGIC_VECTOR (12 downto 0);
    signal out_count_2_fu_712_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ptr_fu_106 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_ptr_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln83_fu_378_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln76_fu_404_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln83_1_fu_422_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_442_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_450_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_458_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_442_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_476_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_484_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_fu_489_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_496_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_4_fu_501_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_1_fu_511_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_1_fu_519_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_537_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_545_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_2_fu_550_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_2_fu_557_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_6_fu_562_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_3_fu_572_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_3_fu_580_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_598_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_606_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_4_fu_611_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_4_fu_618_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_8_fu_623_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_5_fu_633_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_5_fu_641_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal lhs_6_fu_659_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_6_fu_666_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_s_fu_671_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_7_fu_681_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_7_fu_689_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_442_ce : STD_LOGIC;
    signal grp_fu_450_ce : STD_LOGIC;
    signal grp_fu_458_ce : STD_LOGIC;
    signal grp_fu_476_ce : STD_LOGIC;
    signal grp_fu_484_ce : STD_LOGIC;
    signal grp_fu_537_ce : STD_LOGIC;
    signal grp_fu_545_ce : STD_LOGIC;
    signal grp_fu_598_ce : STD_LOGIC;
    signal grp_fu_606_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_mul_32s_32s_48_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component conv2d_stream_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_48_2_1_U1 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_reg_834,
        din1 => grp_fu_442_p1,
        ce => grp_fu_442_ce,
        dout => grp_fu_442_p2);

    mul_32s_32s_48_2_1_U2 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_1_reg_839,
        din1 => grp_fu_450_p1,
        ce => grp_fu_450_ce,
        dout => grp_fu_450_p2);

    mul_32s_32s_48_2_1_U3 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_2_reg_844,
        din1 => grp_fu_458_p1,
        ce => grp_fu_458_ce,
        dout => grp_fu_458_p2);

    mul_32s_32s_48_2_1_U4 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_reg_849_pp0_iter2_reg,
        din1 => grp_fu_476_p1,
        ce => grp_fu_476_ce,
        dout => grp_fu_476_p2);

    mul_32s_32s_48_2_1_U5 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_1_reg_854_pp0_iter2_reg,
        din1 => grp_fu_484_p1,
        ce => grp_fu_484_ce,
        dout => grp_fu_484_p2);

    mul_32s_32s_48_2_1_U6 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_2_reg_859_pp0_iter3_reg,
        din1 => grp_fu_537_p1,
        ce => grp_fu_537_ce,
        dout => grp_fu_537_p2);

    mul_32s_32s_48_2_1_U7 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_reg_864_pp0_iter3_reg,
        din1 => grp_fu_545_p1,
        ce => grp_fu_545_ce,
        dout => grp_fu_545_p2);

    mul_32s_32s_48_2_1_U8 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_1_reg_869_pp0_iter4_reg,
        din1 => grp_fu_598_p1,
        ce => grp_fu_598_ce,
        dout => grp_fu_598_p2);

    mul_32s_32s_48_2_1_U9 : component conv2d_stream_mul_32s_32s_48_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_2_reg_894_pp0_iter4_reg,
        din1 => grp_fu_606_p1,
        ce => grp_fu_606_ce,
        dout => grp_fu_606_p2);

    flow_control_loop_pipe_sequential_init_U : component conv2d_stream_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    out_count_1_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    out_count_1_fu_102 <= out_count;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    out_count_1_fu_102 <= out_count_2_fu_712_p2;
                end if;
            end if; 
        end if;
    end process;

    ptr_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln69_fu_372_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    ptr_fu_106 <= add_ln83_fu_378_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ptr_fu_106 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                k00_cast_cast_reg_777 <= k00_cast_cast_fu_355_p1;
                k01_cast_cast_reg_772 <= k01_cast_cast_fu_351_p1;
                k02_cast_cast_reg_767 <= k02_cast_cast_fu_347_p1;
                k10_cast_cast_reg_762 <= k10_cast_cast_fu_343_p1;
                k11_cast_cast_reg_757 <= k11_cast_cast_fu_339_p1;
                k12_cast_cast_reg_752 <= k12_cast_cast_fu_335_p1;
                k20_cast_cast_reg_747 <= k20_cast_cast_fu_331_p1;
                k21_cast_cast_reg_742 <= k21_cast_cast_fu_327_p1;
                sext_ln67_cast_reg_737 <= sext_ln67_cast_fu_323_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                linebuf_V_1_load_1_reg_854_pp0_iter2_reg <= linebuf_V_1_load_1_reg_854;
                linebuf_V_1_load_2_reg_859_pp0_iter2_reg <= linebuf_V_1_load_2_reg_859;
                linebuf_V_1_load_2_reg_859_pp0_iter3_reg <= linebuf_V_1_load_2_reg_859_pp0_iter2_reg;
                linebuf_V_1_load_reg_849_pp0_iter2_reg <= linebuf_V_1_load_reg_849;
                linebuf_V_2_load_1_reg_869_pp0_iter2_reg <= linebuf_V_2_load_1_reg_869;
                linebuf_V_2_load_1_reg_869_pp0_iter3_reg <= linebuf_V_2_load_1_reg_869_pp0_iter2_reg;
                linebuf_V_2_load_1_reg_869_pp0_iter4_reg <= linebuf_V_2_load_1_reg_869_pp0_iter3_reg;
                linebuf_V_2_load_2_reg_894_pp0_iter3_reg <= linebuf_V_2_load_2_reg_894;
                linebuf_V_2_load_2_reg_894_pp0_iter4_reg <= linebuf_V_2_load_2_reg_894_pp0_iter3_reg;
                linebuf_V_2_load_reg_864_pp0_iter2_reg <= linebuf_V_2_load_reg_864;
                linebuf_V_2_load_reg_864_pp0_iter3_reg <= linebuf_V_2_load_reg_864_pp0_iter2_reg;
                r_V_1_reg_899 <= grp_fu_450_p2;
                r_V_2_reg_909 <= grp_fu_458_p2;
                r_V_3_reg_924 <= grp_fu_476_p2;
                r_V_4_reg_934 <= grp_fu_484_p2;
                r_V_5_reg_949 <= grp_fu_537_p2;
                r_V_6_reg_959 <= grp_fu_545_p2;
                r_V_7_reg_974 <= grp_fu_598_p2;
                r_V_8_reg_984 <= grp_fu_606_p2;
                tmp_5_reg_929 <= ret_V_1_fu_519_p2(47 downto 16);
                tmp_7_reg_954 <= ret_V_3_fu_580_p2(47 downto 16);
                tmp_9_reg_979 <= ret_V_5_fu_641_p2(47 downto 16);
                tmp_reg_904 <= grp_fu_442_p2(47 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                linebuf_V_0_load_1_reg_839 <= linebuf_V_0_q1;
                linebuf_V_0_load_2_reg_844 <= linebuf_V_0_q0;
                linebuf_V_0_load_reg_834 <= linebuf_V_0_q2;
                linebuf_V_1_load_1_reg_854 <= linebuf_V_1_q1;
                linebuf_V_1_load_2_reg_859 <= linebuf_V_1_q0;
                linebuf_V_1_load_reg_849 <= linebuf_V_1_q2;
                linebuf_V_2_load_1_reg_869 <= linebuf_V_2_q2;
                linebuf_V_2_load_reg_864 <= linebuf_V_2_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                linebuf_V_2_load_2_reg_894 <= linebuf_V_2_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln69_fu_372_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln1168_1_reg_799(6 downto 0) <= zext_ln1168_1_fu_428_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln1168_1_reg_799(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_fu_404_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_2));
    add_ln83_1_fu_422_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_2));
    add_ln83_fu_378_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op47_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op47_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op47_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op47_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op47_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op47_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, ap_predicate_op47_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_predicate_op47_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter7_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln69_fu_372_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln69_fu_372_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op47_read_state1_assign_proc : process(icmp_ln69_fu_372_p2, tmp_1_fu_391_p3)
    begin
                ap_predicate_op47_read_state1 <= ((tmp_1_fu_391_p3 = ap_const_lv1_0) and (icmp_ln69_fu_372_p2 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ptr_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ptr_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ptr_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_ptr_1 <= ptr_fu_106;
        end if; 
    end process;


    grp_fu_442_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_442_ce <= ap_const_logic_1;
        else 
            grp_fu_442_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_442_p1 <= k00_cast_cast_reg_777(32 - 1 downto 0);

    grp_fu_450_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_450_ce <= ap_const_logic_1;
        else 
            grp_fu_450_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_450_p1 <= k01_cast_cast_reg_772(32 - 1 downto 0);

    grp_fu_458_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_458_ce <= ap_const_logic_1;
        else 
            grp_fu_458_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_458_p1 <= k02_cast_cast_reg_767(32 - 1 downto 0);

    grp_fu_476_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_476_ce <= ap_const_logic_1;
        else 
            grp_fu_476_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_476_p1 <= k10_cast_cast_reg_762(32 - 1 downto 0);

    grp_fu_484_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_484_ce <= ap_const_logic_1;
        else 
            grp_fu_484_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_484_p1 <= k11_cast_cast_reg_757(32 - 1 downto 0);

    grp_fu_537_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_537_ce <= ap_const_logic_1;
        else 
            grp_fu_537_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_537_p1 <= k12_cast_cast_reg_752(32 - 1 downto 0);

    grp_fu_545_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_545_ce <= ap_const_logic_1;
        else 
            grp_fu_545_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_545_p1 <= k20_cast_cast_reg_747(32 - 1 downto 0);

    grp_fu_598_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_598_ce <= ap_const_logic_1;
        else 
            grp_fu_598_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_598_p1 <= k21_cast_cast_reg_742(32 - 1 downto 0);

    grp_fu_606_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_606_ce <= ap_const_logic_1;
        else 
            grp_fu_606_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_606_p1 <= sext_ln67_cast_reg_737(32 - 1 downto 0);
    icmp_ln69_fu_372_p2 <= "1" when (ap_sig_allocacmp_ptr_1 = ap_const_lv7_42) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, in_stream_TVALID, ap_predicate_op47_read_state1, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op47_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op47_read_state1, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op47_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

        k00_cast_cast_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k00_cast),48));

        k01_cast_cast_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k01_cast),48));

        k02_cast_cast_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k02_cast),48));

        k10_cast_cast_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k10_cast),48));

        k11_cast_cast_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k11_cast),48));

        k12_cast_cast_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k12_cast),48));

        k20_cast_cast_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k20_cast),48));

        k21_cast_cast_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k21_cast),48));

    lhs_1_fu_511_p3 <= (tmp_4_fu_501_p4 & ap_const_lv16_0);
    lhs_2_fu_550_p3 <= (tmp_5_reg_929 & ap_const_lv16_0);
    lhs_3_fu_572_p3 <= (tmp_6_fu_562_p4 & ap_const_lv16_0);
    lhs_4_fu_611_p3 <= (tmp_7_reg_954 & ap_const_lv16_0);
    lhs_5_fu_633_p3 <= (tmp_8_fu_623_p4 & ap_const_lv16_0);
    lhs_6_fu_659_p3 <= (tmp_9_reg_979 & ap_const_lv16_0);
    lhs_7_fu_681_p3 <= (tmp_s_fu_671_p4 & ap_const_lv16_0);
    lhs_fu_489_p3 <= (tmp_reg_904 & ap_const_lv16_0);
    linebuf_V_0_address0 <= zext_ln1168_1_fu_428_p1(7 - 1 downto 0);
    linebuf_V_0_address1 <= zext_ln1168_fu_415_p1(7 - 1 downto 0);
    linebuf_V_0_address2 <= zext_ln69_fu_384_p1(7 - 1 downto 0);

    linebuf_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce2 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_1_address0 <= zext_ln1168_1_fu_428_p1(7 - 1 downto 0);
    linebuf_V_1_address1 <= zext_ln1168_fu_415_p1(7 - 1 downto 0);
    linebuf_V_1_address2 <= zext_ln69_fu_384_p1(7 - 1 downto 0);

    linebuf_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce2 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_2_address0 <= zext_ln76_fu_410_p1(7 - 1 downto 0);
    linebuf_V_2_address1 <= zext_ln1168_1_reg_799(7 - 1 downto 0);
    linebuf_V_2_address2 <= zext_ln1168_fu_415_p1(7 - 1 downto 0);
    linebuf_V_2_address3 <= zext_ln69_fu_384_p1(7 - 1 downto 0);

    linebuf_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce3 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_2_d0 <= in_stream_TDATA;

    linebuf_V_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln69_fu_372_p2, tmp_1_fu_391_p3, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_1_fu_391_p3 = ap_const_lv1_0) and (icmp_ln69_fu_372_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_we0 <= ap_const_logic_1;
        else 
            linebuf_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_count_2_fu_712_p2 <= std_logic_vector(unsigned(out_count_1_fu_102) + unsigned(ap_const_lv13_1));
    out_stream_TDATA <= ret_V_7_fu_689_p2(47 downto 16);

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TKEEP <= ap_const_lv4_F;
    out_stream_TLAST <= "1" when (out_count_1_fu_102 = ap_const_lv13_1103) else "0";
    out_stream_TSTRB <= ap_const_lv4_F;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_1_fu_519_p2 <= std_logic_vector(unsigned(lhs_1_fu_511_p3) + unsigned(r_V_2_reg_909));
    ret_V_2_fu_557_p2 <= std_logic_vector(unsigned(lhs_2_fu_550_p3) + unsigned(r_V_3_reg_924));
    ret_V_3_fu_580_p2 <= std_logic_vector(unsigned(lhs_3_fu_572_p3) + unsigned(r_V_4_reg_934));
    ret_V_4_fu_618_p2 <= std_logic_vector(unsigned(lhs_4_fu_611_p3) + unsigned(r_V_5_reg_949));
    ret_V_5_fu_641_p2 <= std_logic_vector(unsigned(lhs_5_fu_633_p3) + unsigned(r_V_6_reg_959));
    ret_V_6_fu_666_p2 <= std_logic_vector(unsigned(lhs_6_fu_659_p3) + unsigned(r_V_7_reg_974));
    ret_V_7_fu_689_p2 <= std_logic_vector(unsigned(lhs_7_fu_681_p3) + unsigned(r_V_8_reg_984));
    ret_V_fu_496_p2 <= std_logic_vector(unsigned(lhs_fu_489_p3) + unsigned(r_V_1_reg_899));
        sext_ln67_cast_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln67),48));

    tmp_1_fu_391_p3 <= ap_sig_allocacmp_ptr_1(6 downto 6);
    tmp_4_fu_501_p4 <= ret_V_fu_496_p2(47 downto 16);
    tmp_6_fu_562_p4 <= ret_V_2_fu_557_p2(47 downto 16);
    tmp_8_fu_623_p4 <= ret_V_4_fu_618_p2(47 downto 16);
    tmp_s_fu_671_p4 <= ret_V_6_fu_666_p2(47 downto 16);
    zext_ln1168_1_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln83_1_fu_422_p2),64));
    zext_ln1168_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln83_fu_378_p2),64));
    zext_ln69_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ptr_1),64));
    zext_ln76_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_404_p2),64));
end behav;
