-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_count : IN STD_LOGIC_VECTOR (12 downto 0);
    linebuf_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce0 : OUT STD_LOGIC;
    linebuf_V_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce1 : OUT STD_LOGIC;
    linebuf_V_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_0_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_0_ce2 : OUT STD_LOGIC;
    linebuf_V_0_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    k00 : IN STD_LOGIC_VECTOR (31 downto 0);
    k01 : IN STD_LOGIC_VECTOR (31 downto 0);
    k02 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce0 : OUT STD_LOGIC;
    linebuf_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce1 : OUT STD_LOGIC;
    linebuf_V_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_1_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_1_ce2 : OUT STD_LOGIC;
    linebuf_V_1_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    k10 : IN STD_LOGIC_VECTOR (31 downto 0);
    k11 : IN STD_LOGIC_VECTOR (31 downto 0);
    k12 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce0 : OUT STD_LOGIC;
    linebuf_V_2_we0 : OUT STD_LOGIC;
    linebuf_V_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce1 : OUT STD_LOGIC;
    linebuf_V_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce2 : OUT STD_LOGIC;
    linebuf_V_2_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    linebuf_V_2_address3 : OUT STD_LOGIC_VECTOR (6 downto 0);
    linebuf_V_2_ce3 : OUT STD_LOGIC;
    linebuf_V_2_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    k20 : IN STD_LOGIC_VECTOR (31 downto 0);
    k21 : IN STD_LOGIC_VECTOR (31 downto 0);
    k22 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_42 : STD_LOGIC_VECTOR (6 downto 0) := "1000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv13_1103 : STD_LOGIC_VECTOR (12 downto 0) := "1000100000011";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln51_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_345_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op38_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln225_1_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_1_reg_562 : STD_LOGIC_VECTOR (63 downto 0);
    signal linebuf_V_0_load_reg_597 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_load_1_reg_602 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_0_load_2_reg_607 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_reg_612 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_1_reg_617 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_1_load_2_reg_622 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_reg_627 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_1_reg_632 : STD_LOGIC_VECTOR (31 downto 0);
    signal linebuf_V_2_load_2_reg_642 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_393_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_reg_647 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_397_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_1_reg_652 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_401_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_2_reg_657 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_405_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_3_reg_662 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_409_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_4_reg_667 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_4_reg_667_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_4_reg_667_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_5_reg_672 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_5_reg_672_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_5_reg_672_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_6_reg_677 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_6_reg_677_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_421_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_7_reg_682 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_7_reg_682_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_425_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln870_8_reg_687 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_fu_429_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_reg_692 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_reg_692_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_reg_692_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_1_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_1_reg_697 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_1_reg_697_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_1_reg_697_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_5_fu_441_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_5_reg_702 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_6_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_6_reg_707 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln58_fu_364_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln51_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_fu_369_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_count_1_fu_92 : STD_LOGIC_VECTOR (12 downto 0);
    signal out_count_2_fu_475_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ptr_fu_96 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_ptr_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln65_fu_332_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln58_fu_358_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln65_1_fu_376_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln870_4_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_3_fu_446_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln870_2_fu_458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_393_ce : STD_LOGIC;
    signal grp_fu_397_ce : STD_LOGIC;
    signal grp_fu_401_ce : STD_LOGIC;
    signal grp_fu_405_ce : STD_LOGIC;
    signal grp_fu_409_ce : STD_LOGIC;
    signal grp_fu_413_ce : STD_LOGIC;
    signal grp_fu_417_ce : STD_LOGIC;
    signal grp_fu_421_ce : STD_LOGIC;
    signal grp_fu_425_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_2_1_U1 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_reg_597,
        din1 => k00,
        ce => grp_fu_393_ce,
        dout => grp_fu_393_p2);

    mul_32s_32s_32_2_1_U2 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_1_reg_602,
        din1 => k01,
        ce => grp_fu_397_ce,
        dout => grp_fu_397_p2);

    mul_32s_32s_32_2_1_U3 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_0_load_2_reg_607,
        din1 => k02,
        ce => grp_fu_401_ce,
        dout => grp_fu_401_p2);

    mul_32s_32s_32_2_1_U4 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_reg_612,
        din1 => k10,
        ce => grp_fu_405_ce,
        dout => grp_fu_405_p2);

    mul_32s_32s_32_2_1_U5 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_1_reg_617,
        din1 => k11,
        ce => grp_fu_409_ce,
        dout => grp_fu_409_p2);

    mul_32s_32s_32_2_1_U6 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_1_load_2_reg_622,
        din1 => k12,
        ce => grp_fu_413_ce,
        dout => grp_fu_413_p2);

    mul_32s_32s_32_2_1_U7 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_reg_627,
        din1 => k20,
        ce => grp_fu_417_ce,
        dout => grp_fu_417_p2);

    mul_32s_32s_32_2_1_U8 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_1_reg_632,
        din1 => k21,
        ce => grp_fu_421_ce,
        dout => grp_fu_421_p2);

    mul_32s_32s_32_2_1_U9 : component conv2d_stream_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => linebuf_V_2_load_2_reg_642,
        din1 => k22,
        ce => grp_fu_425_ce,
        dout => grp_fu_425_p2);

    flow_control_loop_pipe_sequential_init_U : component conv2d_stream_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    out_count_1_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    out_count_1_fu_92 <= out_count;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    out_count_1_fu_92 <= out_count_2_fu_475_p2;
                end if;
            end if; 
        end if;
    end process;

    ptr_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln51_fu_326_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    ptr_fu_96 <= add_ln65_fu_332_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ptr_fu_96 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln870_1_reg_697 <= add_ln870_1_fu_433_p2;
                add_ln870_1_reg_697_pp0_iter5_reg <= add_ln870_1_reg_697;
                add_ln870_1_reg_697_pp0_iter6_reg <= add_ln870_1_reg_697_pp0_iter5_reg;
                add_ln870_5_reg_702 <= add_ln870_5_fu_441_p2;
                add_ln870_6_reg_707 <= add_ln870_6_fu_450_p2;
                add_ln870_reg_692 <= add_ln870_fu_429_p2;
                add_ln870_reg_692_pp0_iter5_reg <= add_ln870_reg_692;
                add_ln870_reg_692_pp0_iter6_reg <= add_ln870_reg_692_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                mul_ln870_1_reg_652 <= grp_fu_397_p2;
                mul_ln870_2_reg_657 <= grp_fu_401_p2;
                mul_ln870_3_reg_662 <= grp_fu_405_p2;
                mul_ln870_4_reg_667 <= grp_fu_409_p2;
                mul_ln870_4_reg_667_pp0_iter4_reg <= mul_ln870_4_reg_667;
                mul_ln870_4_reg_667_pp0_iter5_reg <= mul_ln870_4_reg_667_pp0_iter4_reg;
                mul_ln870_5_reg_672 <= grp_fu_413_p2;
                mul_ln870_5_reg_672_pp0_iter4_reg <= mul_ln870_5_reg_672;
                mul_ln870_5_reg_672_pp0_iter5_reg <= mul_ln870_5_reg_672_pp0_iter4_reg;
                mul_ln870_6_reg_677 <= grp_fu_417_p2;
                mul_ln870_6_reg_677_pp0_iter4_reg <= mul_ln870_6_reg_677;
                mul_ln870_7_reg_682 <= grp_fu_421_p2;
                mul_ln870_7_reg_682_pp0_iter4_reg <= mul_ln870_7_reg_682;
                mul_ln870_8_reg_687 <= grp_fu_425_p2;
                mul_ln870_reg_647 <= grp_fu_393_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                linebuf_V_0_load_1_reg_602 <= linebuf_V_0_q1;
                linebuf_V_0_load_2_reg_607 <= linebuf_V_0_q0;
                linebuf_V_0_load_reg_597 <= linebuf_V_0_q2;
                linebuf_V_1_load_1_reg_617 <= linebuf_V_1_q1;
                linebuf_V_1_load_2_reg_622 <= linebuf_V_1_q0;
                linebuf_V_1_load_reg_612 <= linebuf_V_1_q2;
                linebuf_V_2_load_1_reg_632 <= linebuf_V_2_q2;
                linebuf_V_2_load_reg_627 <= linebuf_V_2_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                linebuf_V_2_load_2_reg_642 <= linebuf_V_2_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln51_fu_326_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln225_1_reg_562(6 downto 0) <= zext_ln225_1_fu_382_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln225_1_reg_562(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_fu_358_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_2));
    add_ln65_1_fu_376_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_2));
    add_ln65_fu_332_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ptr_1) + unsigned(ap_const_lv7_1));
    add_ln870_1_fu_433_p2 <= std_logic_vector(unsigned(mul_ln870_2_reg_657) + unsigned(mul_ln870_3_reg_662));
    add_ln870_2_fu_458_p2 <= std_logic_vector(unsigned(add_ln870_1_reg_697_pp0_iter6_reg) + unsigned(add_ln870_reg_692_pp0_iter6_reg));
    add_ln870_3_fu_446_p2 <= std_logic_vector(unsigned(mul_ln870_4_reg_667_pp0_iter5_reg) + unsigned(mul_ln870_5_reg_672_pp0_iter5_reg));
    add_ln870_4_fu_437_p2 <= std_logic_vector(unsigned(mul_ln870_7_reg_682_pp0_iter4_reg) + unsigned(mul_ln870_8_reg_687));
    add_ln870_5_fu_441_p2 <= std_logic_vector(unsigned(add_ln870_4_fu_437_p2) + unsigned(mul_ln870_6_reg_677_pp0_iter4_reg));
    add_ln870_6_fu_450_p2 <= std_logic_vector(unsigned(add_ln870_5_reg_702) + unsigned(add_ln870_3_fu_446_p2));
    add_ln870_fu_429_p2 <= std_logic_vector(unsigned(mul_ln870_1_reg_652) + unsigned(mul_ln870_reg_647));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op38_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op38_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, in_stream_TVALID, ap_predicate_op38_read_state1, out_stream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, ap_predicate_op38_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_predicate_op38_read_state1 = ap_const_boolean_1) and (in_stream_TVALID = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter7_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln51_fu_326_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln51_fu_326_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op38_read_state1_assign_proc : process(icmp_ln51_fu_326_p2, tmp_fu_345_p3)
    begin
                ap_predicate_op38_read_state1 <= ((tmp_fu_345_p3 = ap_const_lv1_0) and (icmp_ln51_fu_326_p2 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ptr_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ptr_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ptr_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_ptr_1 <= ptr_fu_96;
        end if; 
    end process;


    grp_fu_393_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_393_ce <= ap_const_logic_1;
        else 
            grp_fu_393_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_397_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_397_ce <= ap_const_logic_1;
        else 
            grp_fu_397_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_401_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_401_ce <= ap_const_logic_1;
        else 
            grp_fu_401_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_405_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_405_ce <= ap_const_logic_1;
        else 
            grp_fu_405_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_409_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_409_ce <= ap_const_logic_1;
        else 
            grp_fu_409_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_413_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_413_ce <= ap_const_logic_1;
        else 
            grp_fu_413_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_417_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_417_ce <= ap_const_logic_1;
        else 
            grp_fu_417_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_421_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_421_ce <= ap_const_logic_1;
        else 
            grp_fu_421_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_425_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_425_ce <= ap_const_logic_1;
        else 
            grp_fu_425_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln51_fu_326_p2 <= "1" when (ap_sig_allocacmp_ptr_1 = ap_const_lv7_42) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, in_stream_TVALID, ap_predicate_op38_read_state1, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op38_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op38_read_state1, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op38_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_0_address0 <= zext_ln225_1_fu_382_p1(7 - 1 downto 0);
    linebuf_V_0_address1 <= zext_ln225_fu_369_p1(7 - 1 downto 0);
    linebuf_V_0_address2 <= zext_ln51_fu_338_p1(7 - 1 downto 0);

    linebuf_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_0_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_0_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_0_ce2 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_1_address0 <= zext_ln225_1_fu_382_p1(7 - 1 downto 0);
    linebuf_V_1_address1 <= zext_ln225_fu_369_p1(7 - 1 downto 0);
    linebuf_V_1_address2 <= zext_ln51_fu_338_p1(7 - 1 downto 0);

    linebuf_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_1_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_1_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_1_ce2 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_2_address0 <= zext_ln58_fu_364_p1(7 - 1 downto 0);
    linebuf_V_2_address1 <= zext_ln225_1_reg_562(7 - 1 downto 0);
    linebuf_V_2_address2 <= zext_ln225_fu_369_p1(7 - 1 downto 0);
    linebuf_V_2_address3 <= zext_ln51_fu_338_p1(7 - 1 downto 0);

    linebuf_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce0 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce1 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce2 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_V_2_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_ce3 <= ap_const_logic_1;
        else 
            linebuf_V_2_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_V_2_d0 <= in_stream_TDATA;

    linebuf_V_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln51_fu_326_p2, tmp_fu_345_p3, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_fu_345_p3 = ap_const_lv1_0) and (icmp_ln51_fu_326_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_V_2_we0 <= ap_const_logic_1;
        else 
            linebuf_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_count_2_fu_475_p2 <= std_logic_vector(unsigned(out_count_1_fu_92) + unsigned(ap_const_lv13_1));
    out_stream_TDATA <= std_logic_vector(unsigned(add_ln870_6_reg_707) + unsigned(add_ln870_2_fu_458_p2));

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TKEEP <= ap_const_lv4_F;
    out_stream_TLAST <= "1" when (out_count_1_fu_92 = ap_const_lv13_1103) else "0";
    out_stream_TSTRB <= ap_const_lv4_F;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_345_p3 <= ap_sig_allocacmp_ptr_1(6 downto 6);
    zext_ln225_1_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln65_1_fu_376_p2),64));
    zext_ln225_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln65_fu_332_p2),64));
    zext_ln51_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ptr_1),64));
    zext_ln58_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_fu_358_p2),64));
end behav;
