// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_stream_conv2d_stream,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4766,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=149252,HLS_SYN_LUT=63292,HLS_VERSION=2021_1}" *)

module conv2d_stream (
// synthesis translate_off
    kernel_block,
// synthesis translate_on
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

// synthesis translate_off
output kernel_block;
// synthesis translate_on
input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] k00;
wire   [31:0] k01;
wire   [31:0] k02;
wire   [31:0] k10;
wire   [31:0] k11;
wire   [31:0] k12;
wire   [31:0] k20;
wire   [31:0] k21;
wire   [31:0] k22;
reg   [31:0] k22_read_reg_312;
reg   [31:0] k21_read_reg_317;
reg   [31:0] k20_read_reg_322;
reg   [31:0] k12_read_reg_327;
reg   [31:0] k11_read_reg_332;
reg   [31:0] k10_read_reg_337;
reg   [31:0] k02_read_reg_342;
reg   [31:0] k01_read_reg_347;
reg   [31:0] k00_read_reg_352;
reg   [1:0] r_1_reg_357;
wire    ap_CS_fsm_state2;
wire   [1:0] add_ln57_fu_276_p2;
reg   [1:0] add_ln57_reg_364;
wire   [6:0] add_ln59_fu_295_p2;
wire    ap_CS_fsm_state3;
reg   [6:0] linebuf_V_0_address0;
reg    linebuf_V_0_ce0;
reg    linebuf_V_0_we0;
reg   [31:0] linebuf_V_0_d0;
wire   [31:0] linebuf_V_0_q0;
reg    linebuf_V_0_ce1;
reg    linebuf_V_0_we1;
wire   [31:0] linebuf_V_0_q1;
reg   [6:0] linebuf_V_1_address0;
reg    linebuf_V_1_ce0;
reg    linebuf_V_1_we0;
reg   [31:0] linebuf_V_1_d0;
wire   [31:0] linebuf_V_1_q0;
reg    linebuf_V_1_ce1;
reg    linebuf_V_1_we1;
wire   [31:0] linebuf_V_1_q1;
reg   [6:0] linebuf_V_2_address0;
reg    linebuf_V_2_ce0;
reg    linebuf_V_2_we0;
reg   [31:0] linebuf_V_2_d0;
wire   [31:0] linebuf_V_2_q0;
reg    linebuf_V_2_ce1;
reg    linebuf_V_2_we1;
wire   [31:0] linebuf_V_2_q1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_done;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_idle;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_ready;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TREADY;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we1;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d1;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we1;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d1;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce0;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we1;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d1;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_in_stream_TREADY;
wire   [31:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TDATA;
wire    grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID;
wire   [3:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TKEEP;
wire   [3:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TSTRB;
wire   [0:0] grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TLAST;
reg   [6:0] c_reg_219;
wire   [0:0] icmp_ln57_fu_270_p2;
wire   [0:0] icmp_ln59_fu_289_p2;
reg    grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln59_fu_282_p1;
reg   [1:0] r_fu_110;
wire    ap_CS_fsm_state6;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg = 1'b0;
end

conv2d_stream_linebuf_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_0_address0),
    .ce0(linebuf_V_0_ce0),
    .we0(linebuf_V_0_we0),
    .d0(linebuf_V_0_d0),
    .q0(linebuf_V_0_q0),
    .address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address1),
    .ce1(linebuf_V_0_ce1),
    .we1(linebuf_V_0_we1),
    .d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d1),
    .q1(linebuf_V_0_q1)
);

conv2d_stream_linebuf_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_1_address0),
    .ce0(linebuf_V_1_ce0),
    .we0(linebuf_V_1_we0),
    .d0(linebuf_V_1_d0),
    .q0(linebuf_V_1_q0),
    .address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address1),
    .ce1(linebuf_V_1_ce1),
    .we1(linebuf_V_1_we1),
    .d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d1),
    .q1(linebuf_V_1_q1)
);

conv2d_stream_linebuf_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_2_address0),
    .ce0(linebuf_V_2_ce0),
    .we0(linebuf_V_2_we0),
    .d0(linebuf_V_2_d0),
    .q0(linebuf_V_2_q0),
    .address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address1),
    .ce1(linebuf_V_2_ce1),
    .we1(linebuf_V_2_we1),
    .d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d1),
    .q1(linebuf_V_2_q1)
);

conv2d_stream_conv2d_stream_Pipeline_each_image_row grp_conv2d_stream_Pipeline_each_image_row_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start),
    .ap_done(grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_done),
    .ap_idle(grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_idle),
    .ap_ready(grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_ready),
    .out_stream_TREADY(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TREADY),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .linebuf_V_2_address0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address0),
    .linebuf_V_2_ce0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce0),
    .linebuf_V_2_we0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we0),
    .linebuf_V_2_d0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d0),
    .linebuf_V_2_q0(linebuf_V_2_q0),
    .linebuf_V_2_address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address1),
    .linebuf_V_2_ce1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce1),
    .linebuf_V_2_we1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we1),
    .linebuf_V_2_d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d1),
    .linebuf_V_2_q1(linebuf_V_2_q1),
    .linebuf_V_1_address0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address0),
    .linebuf_V_1_ce0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce0),
    .linebuf_V_1_we0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we0),
    .linebuf_V_1_d0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d0),
    .linebuf_V_1_q0(linebuf_V_1_q0),
    .linebuf_V_1_address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address1),
    .linebuf_V_1_ce1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce1),
    .linebuf_V_1_we1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we1),
    .linebuf_V_1_d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d1),
    .linebuf_V_1_q1(linebuf_V_1_q1),
    .linebuf_V_0_address0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address0),
    .linebuf_V_0_ce0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce0),
    .linebuf_V_0_we0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we0),
    .linebuf_V_0_d0(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d0),
    .linebuf_V_0_q0(linebuf_V_0_q0),
    .linebuf_V_0_address1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address1),
    .linebuf_V_0_ce1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce1),
    .linebuf_V_0_we1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we1),
    .linebuf_V_0_d1(grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d1),
    .linebuf_V_0_q1(linebuf_V_0_q1),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_conv2d_stream_Pipeline_each_image_row_fu_230_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .sext_ln1171(k00_read_reg_352),
    .sext_ln1171_1(k01_read_reg_347),
    .sext_ln1171_2(k02_read_reg_342),
    .sext_ln1171_3(k10_read_reg_337),
    .sext_ln1171_4(k11_read_reg_332),
    .sext_ln1171_5(k12_read_reg_327),
    .sext_ln1171_6(k20_read_reg_322),
    .sext_ln1171_7(k21_read_reg_317),
    .sext_ln76(k22_read_reg_312),
    .out_stream_TDATA(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TDATA),
    .out_stream_TVALID(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID),
    .out_stream_TKEEP(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TKEEP),
    .out_stream_TSTRB(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TSTRB),
    .out_stream_TLAST(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TLAST)
);

conv2d_stream_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .k00(k00),
    .k01(k01),
    .k02(k02),
    .k10(k10),
    .k11(k11),
    .k12(k12),
    .k20(k20),
    .k21(k21),
    .k22(k22),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TDATA),
    .vld_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TKEEP),
    .vld_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TSTRB),
    .vld_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TLAST),
    .vld_in(grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_ready == 1'b1)) begin
            grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        c_reg_219 <= add_ln59_fu_295_p2;
    end else if (((icmp_ln57_fu_270_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        c_reg_219 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        r_fu_110 <= 2'd0;
    end else if (((icmp_ln59_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_fu_110 <= add_ln57_reg_364;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln57_reg_364 <= add_ln57_fu_276_p2;
        r_1_reg_357 <= r_fu_110;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        k00_read_reg_352 <= k00;
        k01_read_reg_347 <= k01;
        k02_read_reg_342 <= k02;
        k10_read_reg_337 <= k10;
        k11_read_reg_332 <= k11;
        k12_read_reg_327 <= k12;
        k20_read_reg_322 <= k20;
        k21_read_reg_317 <= k21;
        k22_read_reg_312 <= k22;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_stream_TREADY_int_regslice = grp_conv2d_stream_Pipeline_each_image_row_fu_230_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_address0 = zext_ln59_fu_282_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_address0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_address0;
    end else begin
        linebuf_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_ce0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce0;
    end else begin
        linebuf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_ce1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_ce1;
    end else begin
        linebuf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_d0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_d0;
    end else begin
        linebuf_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((r_1_reg_357 == 2'd0) & (icmp_ln59_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_we0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we0;
    end else begin
        linebuf_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_we1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_0_we1;
    end else begin
        linebuf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_address0 = zext_ln59_fu_282_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_address0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_address0;
    end else begin
        linebuf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_ce0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce0;
    end else begin
        linebuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_ce1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_ce1;
    end else begin
        linebuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_d0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_d0;
    end else begin
        linebuf_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((r_1_reg_357 == 2'd1) & (icmp_ln59_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_we0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we0;
    end else begin
        linebuf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_we1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_1_we1;
    end else begin
        linebuf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_address0 = zext_ln59_fu_282_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_address0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_address0;
    end else begin
        linebuf_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce0;
    end else begin
        linebuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_ce1;
    end else begin
        linebuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_d0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_d0;
    end else begin
        linebuf_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~(r_1_reg_357 == 2'd0) & ~(r_1_reg_357 == 2'd1) & (icmp_ln59_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_we0 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we0;
    end else begin
        linebuf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_we1 = grp_conv2d_stream_Pipeline_each_image_row_fu_230_linebuf_V_2_we1;
    end else begin
        linebuf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln57_fu_270_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln59_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_fu_276_p2 = (r_fu_110 + 2'd1);

assign add_ln59_fu_295_p2 = (c_reg_219 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start = grp_conv2d_stream_Pipeline_each_image_row_fu_230_ap_start_reg;

assign grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state5);

assign icmp_ln57_fu_270_p2 = ((r_fu_110 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_289_p2 = ((c_reg_219 == 7'd68) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_conv2d_stream_Pipeline_each_image_row_fu_230_out_stream_TVALID;

assign zext_ln59_fu_282_p1 = c_reg_219;


// synthesis translate_off
`include "conv2d_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //conv2d_stream

