// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        out_count,
        linebuf_V_0_address0,
        linebuf_V_0_ce0,
        linebuf_V_0_q0,
        linebuf_V_0_address1,
        linebuf_V_0_ce1,
        linebuf_V_0_q1,
        linebuf_V_0_address2,
        linebuf_V_0_ce2,
        linebuf_V_0_q2,
        k00,
        k01,
        k02,
        linebuf_V_1_address0,
        linebuf_V_1_ce0,
        linebuf_V_1_q0,
        linebuf_V_1_address1,
        linebuf_V_1_ce1,
        linebuf_V_1_q1,
        linebuf_V_1_address2,
        linebuf_V_1_ce2,
        linebuf_V_1_q2,
        k10,
        k11,
        k12,
        linebuf_V_2_address0,
        linebuf_V_2_ce0,
        linebuf_V_2_we0,
        linebuf_V_2_d0,
        linebuf_V_2_address1,
        linebuf_V_2_ce1,
        linebuf_V_2_q1,
        linebuf_V_2_address2,
        linebuf_V_2_ce2,
        linebuf_V_2_q2,
        linebuf_V_2_address3,
        linebuf_V_2_ce3,
        linebuf_V_2_q3,
        k20,
        k21,
        k22,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [12:0] out_count;
output  [6:0] linebuf_V_0_address0;
output   linebuf_V_0_ce0;
input  [31:0] linebuf_V_0_q0;
output  [6:0] linebuf_V_0_address1;
output   linebuf_V_0_ce1;
input  [31:0] linebuf_V_0_q1;
output  [6:0] linebuf_V_0_address2;
output   linebuf_V_0_ce2;
input  [31:0] linebuf_V_0_q2;
input  [31:0] k00;
input  [31:0] k01;
input  [31:0] k02;
output  [6:0] linebuf_V_1_address0;
output   linebuf_V_1_ce0;
input  [31:0] linebuf_V_1_q0;
output  [6:0] linebuf_V_1_address1;
output   linebuf_V_1_ce1;
input  [31:0] linebuf_V_1_q1;
output  [6:0] linebuf_V_1_address2;
output   linebuf_V_1_ce2;
input  [31:0] linebuf_V_1_q2;
input  [31:0] k10;
input  [31:0] k11;
input  [31:0] k12;
output  [6:0] linebuf_V_2_address0;
output   linebuf_V_2_ce0;
output   linebuf_V_2_we0;
output  [31:0] linebuf_V_2_d0;
output  [6:0] linebuf_V_2_address1;
output   linebuf_V_2_ce1;
input  [31:0] linebuf_V_2_q1;
output  [6:0] linebuf_V_2_address2;
output   linebuf_V_2_ce2;
input  [31:0] linebuf_V_2_q2;
output  [6:0] linebuf_V_2_address3;
output   linebuf_V_2_ce3;
input  [31:0] linebuf_V_2_q3;
input  [31:0] k20;
input  [31:0] k21;
input  [31:0] k22;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;

reg ap_idle;
reg linebuf_V_0_ce0;
reg linebuf_V_0_ce1;
reg linebuf_V_0_ce2;
reg linebuf_V_1_ce0;
reg linebuf_V_1_ce1;
reg linebuf_V_1_ce2;
reg linebuf_V_2_ce0;
reg linebuf_V_2_we0;
reg linebuf_V_2_ce1;
reg linebuf_V_2_ce2;
reg linebuf_V_2_ce3;
reg out_stream_TVALID;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln51_fu_326_p2;
wire   [0:0] tmp_fu_345_p3;
reg    ap_predicate_op38_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    in_stream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln225_1_fu_382_p1;
reg   [63:0] zext_ln225_1_reg_562;
reg  signed [31:0] linebuf_V_0_load_reg_597;
reg  signed [31:0] linebuf_V_0_load_1_reg_602;
reg  signed [31:0] linebuf_V_0_load_2_reg_607;
reg  signed [31:0] linebuf_V_1_load_reg_612;
reg  signed [31:0] linebuf_V_1_load_1_reg_617;
reg  signed [31:0] linebuf_V_1_load_2_reg_622;
reg  signed [31:0] linebuf_V_2_load_reg_627;
reg  signed [31:0] linebuf_V_2_load_1_reg_632;
reg  signed [31:0] linebuf_V_2_load_2_reg_642;
wire   [31:0] grp_fu_393_p2;
reg   [31:0] mul_ln870_reg_647;
wire   [31:0] grp_fu_397_p2;
reg   [31:0] mul_ln870_1_reg_652;
wire   [31:0] grp_fu_401_p2;
reg   [31:0] mul_ln870_2_reg_657;
wire   [31:0] grp_fu_405_p2;
reg   [31:0] mul_ln870_3_reg_662;
wire   [31:0] grp_fu_409_p2;
reg   [31:0] mul_ln870_4_reg_667;
reg   [31:0] mul_ln870_4_reg_667_pp0_iter4_reg;
reg   [31:0] mul_ln870_4_reg_667_pp0_iter5_reg;
wire   [31:0] grp_fu_413_p2;
reg   [31:0] mul_ln870_5_reg_672;
reg   [31:0] mul_ln870_5_reg_672_pp0_iter4_reg;
reg   [31:0] mul_ln870_5_reg_672_pp0_iter5_reg;
wire   [31:0] grp_fu_417_p2;
reg   [31:0] mul_ln870_6_reg_677;
reg   [31:0] mul_ln870_6_reg_677_pp0_iter4_reg;
wire   [31:0] grp_fu_421_p2;
reg   [31:0] mul_ln870_7_reg_682;
reg   [31:0] mul_ln870_7_reg_682_pp0_iter4_reg;
wire   [31:0] grp_fu_425_p2;
reg   [31:0] mul_ln870_8_reg_687;
wire   [31:0] add_ln870_fu_429_p2;
reg   [31:0] add_ln870_reg_692;
reg   [31:0] add_ln870_reg_692_pp0_iter5_reg;
reg   [31:0] add_ln870_reg_692_pp0_iter6_reg;
wire   [31:0] add_ln870_1_fu_433_p2;
reg   [31:0] add_ln870_1_reg_697;
reg   [31:0] add_ln870_1_reg_697_pp0_iter5_reg;
reg   [31:0] add_ln870_1_reg_697_pp0_iter6_reg;
wire   [31:0] add_ln870_5_fu_441_p2;
reg   [31:0] add_ln870_5_reg_702;
wire   [31:0] add_ln870_6_fu_450_p2;
reg   [31:0] add_ln870_6_reg_707;
wire   [63:0] zext_ln58_fu_364_p1;
wire   [63:0] zext_ln51_fu_338_p1;
wire   [63:0] zext_ln225_fu_369_p1;
reg   [12:0] out_count_1_fu_92;
wire   [12:0] out_count_2_fu_475_p2;
wire    ap_loop_init;
reg   [6:0] ptr_fu_96;
reg   [6:0] ap_sig_allocacmp_ptr_1;
wire   [6:0] add_ln65_fu_332_p2;
reg    ap_block_pp0_stage0_01001;
wire   [6:0] add_ln58_fu_358_p2;
wire   [6:0] add_ln65_1_fu_376_p2;
wire   [31:0] add_ln870_4_fu_437_p2;
wire   [31:0] add_ln870_3_fu_446_p2;
wire   [31:0] add_ln870_2_fu_458_p2;
reg    grp_fu_393_ce;
reg    grp_fu_397_ce;
reg    grp_fu_401_ce;
reg    grp_fu_405_ce;
reg    grp_fu_409_ce;
reg    grp_fu_413_ce;
reg    grp_fu_417_ce;
reg    grp_fu_421_ce;
reg    grp_fu_425_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_reg_597),
    .din1(k00),
    .ce(grp_fu_393_ce),
    .dout(grp_fu_393_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_1_reg_602),
    .din1(k01),
    .ce(grp_fu_397_ce),
    .dout(grp_fu_397_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_0_load_2_reg_607),
    .din1(k02),
    .ce(grp_fu_401_ce),
    .dout(grp_fu_401_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_reg_612),
    .din1(k10),
    .ce(grp_fu_405_ce),
    .dout(grp_fu_405_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_1_reg_617),
    .din1(k11),
    .ce(grp_fu_409_ce),
    .dout(grp_fu_409_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_1_load_2_reg_622),
    .din1(k12),
    .ce(grp_fu_413_ce),
    .dout(grp_fu_413_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_reg_627),
    .din1(k20),
    .ce(grp_fu_417_ce),
    .dout(grp_fu_417_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_1_reg_632),
    .din1(k21),
    .ce(grp_fu_421_ce),
    .dout(grp_fu_421_p2)
);

conv2d_stream_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(linebuf_V_2_load_2_reg_642),
    .din1(k22),
    .ce(grp_fu_425_ce),
    .dout(grp_fu_425_p2)
);

conv2d_stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_count_1_fu_92 <= out_count;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            out_count_1_fu_92 <= out_count_2_fu_475_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln51_fu_326_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            ptr_fu_96 <= add_ln65_fu_332_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ptr_fu_96 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln870_1_reg_697 <= add_ln870_1_fu_433_p2;
        add_ln870_1_reg_697_pp0_iter5_reg <= add_ln870_1_reg_697;
        add_ln870_1_reg_697_pp0_iter6_reg <= add_ln870_1_reg_697_pp0_iter5_reg;
        add_ln870_5_reg_702 <= add_ln870_5_fu_441_p2;
        add_ln870_6_reg_707 <= add_ln870_6_fu_450_p2;
        add_ln870_reg_692 <= add_ln870_fu_429_p2;
        add_ln870_reg_692_pp0_iter5_reg <= add_ln870_reg_692;
        add_ln870_reg_692_pp0_iter6_reg <= add_ln870_reg_692_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        mul_ln870_1_reg_652 <= grp_fu_397_p2;
        mul_ln870_2_reg_657 <= grp_fu_401_p2;
        mul_ln870_3_reg_662 <= grp_fu_405_p2;
        mul_ln870_4_reg_667 <= grp_fu_409_p2;
        mul_ln870_4_reg_667_pp0_iter4_reg <= mul_ln870_4_reg_667;
        mul_ln870_4_reg_667_pp0_iter5_reg <= mul_ln870_4_reg_667_pp0_iter4_reg;
        mul_ln870_5_reg_672 <= grp_fu_413_p2;
        mul_ln870_5_reg_672_pp0_iter4_reg <= mul_ln870_5_reg_672;
        mul_ln870_5_reg_672_pp0_iter5_reg <= mul_ln870_5_reg_672_pp0_iter4_reg;
        mul_ln870_6_reg_677 <= grp_fu_417_p2;
        mul_ln870_6_reg_677_pp0_iter4_reg <= mul_ln870_6_reg_677;
        mul_ln870_7_reg_682 <= grp_fu_421_p2;
        mul_ln870_7_reg_682_pp0_iter4_reg <= mul_ln870_7_reg_682;
        mul_ln870_8_reg_687 <= grp_fu_425_p2;
        mul_ln870_reg_647 <= grp_fu_393_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_load_1_reg_602 <= linebuf_V_0_q1;
        linebuf_V_0_load_2_reg_607 <= linebuf_V_0_q0;
        linebuf_V_0_load_reg_597 <= linebuf_V_0_q2;
        linebuf_V_1_load_1_reg_617 <= linebuf_V_1_q1;
        linebuf_V_1_load_2_reg_622 <= linebuf_V_1_q0;
        linebuf_V_1_load_reg_612 <= linebuf_V_1_q2;
        linebuf_V_2_load_1_reg_632 <= linebuf_V_2_q2;
        linebuf_V_2_load_reg_627 <= linebuf_V_2_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        linebuf_V_2_load_2_reg_642 <= linebuf_V_2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln51_fu_326_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln225_1_reg_562[6 : 0] <= zext_ln225_1_fu_382_p1[6 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln51_fu_326_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ptr_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_ptr_1 = ptr_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_393_ce = 1'b1;
    end else begin
        grp_fu_393_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_397_ce = 1'b1;
    end else begin
        grp_fu_397_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_401_ce = 1'b1;
    end else begin
        grp_fu_401_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_405_ce = 1'b1;
    end else begin
        grp_fu_405_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_409_ce = 1'b1;
    end else begin
        grp_fu_409_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_413_ce = 1'b1;
    end else begin
        grp_fu_413_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_417_ce = 1'b1;
    end else begin
        grp_fu_417_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_421_ce = 1'b1;
    end else begin
        grp_fu_421_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_425_ce = 1'b1;
    end else begin
        grp_fu_425_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op38_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op38_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce0 = 1'b1;
    end else begin
        linebuf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce1 = 1'b1;
    end else begin
        linebuf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_0_ce2 = 1'b1;
    end else begin
        linebuf_V_0_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce0 = 1'b1;
    end else begin
        linebuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce1 = 1'b1;
    end else begin
        linebuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_1_ce2 = 1'b1;
    end else begin
        linebuf_V_1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce0 = 1'b1;
    end else begin
        linebuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce1 = 1'b1;
    end else begin
        linebuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce2 = 1'b1;
    end else begin
        linebuf_V_2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_ce3 = 1'b1;
    end else begin
        linebuf_V_2_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_345_p3 == 1'd0) & (icmp_ln51_fu_326_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_V_2_we0 = 1'b1;
    end else begin
        linebuf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_358_p2 = (ap_sig_allocacmp_ptr_1 + 7'd2);

assign add_ln65_1_fu_376_p2 = (ap_sig_allocacmp_ptr_1 + 7'd2);

assign add_ln65_fu_332_p2 = (ap_sig_allocacmp_ptr_1 + 7'd1);

assign add_ln870_1_fu_433_p2 = (mul_ln870_2_reg_657 + mul_ln870_3_reg_662);

assign add_ln870_2_fu_458_p2 = (add_ln870_1_reg_697_pp0_iter6_reg + add_ln870_reg_692_pp0_iter6_reg);

assign add_ln870_3_fu_446_p2 = (mul_ln870_4_reg_667_pp0_iter5_reg + mul_ln870_5_reg_672_pp0_iter5_reg);

assign add_ln870_4_fu_437_p2 = (mul_ln870_7_reg_682_pp0_iter4_reg + mul_ln870_8_reg_687);

assign add_ln870_5_fu_441_p2 = (add_ln870_4_fu_437_p2 + mul_ln870_6_reg_677_pp0_iter4_reg);

assign add_ln870_6_fu_450_p2 = (add_ln870_5_reg_702 + add_ln870_3_fu_446_p2);

assign add_ln870_fu_429_p2 = (mul_ln870_1_reg_652 + mul_ln870_reg_647);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op38_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op38_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op38_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op38_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (out_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op38_read_state1 = ((tmp_fu_345_p3 == 1'd0) & (icmp_ln51_fu_326_p2 == 1'd0));
end

assign icmp_ln51_fu_326_p2 = ((ap_sig_allocacmp_ptr_1 == 7'd66) ? 1'b1 : 1'b0);

assign linebuf_V_0_address0 = zext_ln225_1_fu_382_p1;

assign linebuf_V_0_address1 = zext_ln225_fu_369_p1;

assign linebuf_V_0_address2 = zext_ln51_fu_338_p1;

assign linebuf_V_1_address0 = zext_ln225_1_fu_382_p1;

assign linebuf_V_1_address1 = zext_ln225_fu_369_p1;

assign linebuf_V_1_address2 = zext_ln51_fu_338_p1;

assign linebuf_V_2_address0 = zext_ln58_fu_364_p1;

assign linebuf_V_2_address1 = zext_ln225_1_reg_562;

assign linebuf_V_2_address2 = zext_ln225_fu_369_p1;

assign linebuf_V_2_address3 = zext_ln51_fu_338_p1;

assign linebuf_V_2_d0 = in_stream_TDATA;

assign out_count_2_fu_475_p2 = (out_count_1_fu_92 + 13'd1);

assign out_stream_TDATA = (add_ln870_6_reg_707 + add_ln870_2_fu_458_p2);

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = ((out_count_1_fu_92 == 13'd4355) ? 1'b1 : 1'b0);

assign out_stream_TSTRB = 4'd15;

assign tmp_fu_345_p3 = ap_sig_allocacmp_ptr_1[32'd6];

assign zext_ln225_1_fu_382_p1 = add_ln65_1_fu_376_p2;

assign zext_ln225_fu_369_p1 = add_ln65_fu_332_p2;

assign zext_ln51_fu_338_p1 = ap_sig_allocacmp_ptr_1;

assign zext_ln58_fu_364_p1 = add_ln58_fu_358_p2;

always @ (posedge ap_clk) begin
    zext_ln225_1_reg_562[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right
