// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_stream_conv2d_stream,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=9981,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=3297,HLS_SYN_LUT=2148,HLS_VERSION=2021_1}" *)

module conv2d_stream (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] k00;
wire   [31:0] k01;
wire   [31:0] k02;
wire   [31:0] k10;
wire   [31:0] k11;
wire   [31:0] k12;
wire   [31:0] k20;
wire   [31:0] k21;
wire   [31:0] k22;
reg   [31:0] k22_read_reg_385;
reg   [31:0] k21_read_reg_390;
reg   [31:0] k20_read_reg_395;
reg   [31:0] k12_read_reg_400;
reg   [31:0] k11_read_reg_405;
reg   [31:0] k10_read_reg_410;
reg   [31:0] k02_read_reg_415;
reg   [31:0] k01_read_reg_420;
reg   [31:0] k00_read_reg_425;
reg   [1:0] r_1_reg_430;
wire    ap_CS_fsm_state2;
wire   [1:0] add_ln39_fu_304_p2;
reg   [1:0] add_ln39_reg_437;
wire   [6:0] add_ln41_fu_333_p2;
wire    ap_CS_fsm_state3;
reg   [12:0] out_count_load_reg_467;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln49_fu_346_p2;
reg   [6:0] linebuf_V_0_address0;
reg    linebuf_V_0_ce0;
reg    linebuf_V_0_we0;
reg   [31:0] linebuf_V_0_d0;
wire   [31:0] linebuf_V_0_q0;
reg    linebuf_V_0_ce1;
wire   [31:0] linebuf_V_0_q1;
reg    linebuf_V_0_ce2;
wire   [31:0] linebuf_V_0_q2;
reg   [6:0] linebuf_V_1_address0;
reg    linebuf_V_1_ce0;
reg    linebuf_V_1_we0;
reg   [31:0] linebuf_V_1_d0;
wire   [31:0] linebuf_V_1_q0;
reg   [6:0] linebuf_V_1_address1;
reg    linebuf_V_1_ce1;
wire   [31:0] linebuf_V_1_q1;
reg    linebuf_V_1_ce2;
wire   [31:0] linebuf_V_1_q2;
reg   [6:0] linebuf_V_2_address0;
reg    linebuf_V_2_ce0;
reg    linebuf_V_2_we0;
reg   [31:0] linebuf_V_2_d0;
wire   [31:0] linebuf_V_2_q0;
reg    linebuf_V_2_ce1;
wire   [31:0] linebuf_V_2_q1;
reg    linebuf_V_2_ce2;
wire   [31:0] linebuf_V_2_q2;
reg    linebuf_V_2_ce3;
wire   [31:0] linebuf_V_2_q3;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_idle;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2;
wire   [6:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3;
wire   [31:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID;
wire   [3:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP;
wire   [3:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB;
wire   [0:0] grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST;
wire    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_idle;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready;
wire   [6:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1;
wire   [6:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0;
wire   [6:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0;
wire    grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0;
wire   [31:0] grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0;
reg   [6:0] c_reg_239;
wire   [0:0] icmp_ln41_fu_327_p2;
wire   [0:0] icmp_ln39_fu_298_p2;
reg    grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln41_fu_320_p1;
reg   [1:0] r_fu_122;
reg   [12:0] out_count_fu_138;
wire   [12:0] add_ln51_fu_362_p2;
reg   [6:0] img_r_fu_142;
wire   [6:0] img_r_2_fu_352_p2;
wire    ap_CS_fsm_state8;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg = 1'b0;
#0 grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg = 1'b0;
end

conv2d_stream_linebuf_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_0_address0),
    .ce0(linebuf_V_0_ce0),
    .we0(linebuf_V_0_we0),
    .d0(linebuf_V_0_d0),
    .q0(linebuf_V_0_q0),
    .address1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1),
    .ce1(linebuf_V_0_ce1),
    .q1(linebuf_V_0_q1),
    .address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2),
    .ce2(linebuf_V_0_ce2),
    .q2(linebuf_V_0_q2)
);

conv2d_stream_linebuf_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_1_address0),
    .ce0(linebuf_V_1_ce0),
    .we0(linebuf_V_1_we0),
    .d0(linebuf_V_1_d0),
    .q0(linebuf_V_1_q0),
    .address1(linebuf_V_1_address1),
    .ce1(linebuf_V_1_ce1),
    .q1(linebuf_V_1_q1),
    .address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2),
    .ce2(linebuf_V_1_ce2),
    .q2(linebuf_V_1_q2)
);

conv2d_stream_linebuf_V_2 #(
    .DataWidth( 32 ),
    .AddressRange( 68 ),
    .AddressWidth( 7 ))
linebuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(linebuf_V_2_address0),
    .ce0(linebuf_V_2_ce0),
    .we0(linebuf_V_2_we0),
    .d0(linebuf_V_2_d0),
    .q0(linebuf_V_2_q0),
    .address1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1),
    .ce1(linebuf_V_2_ce1),
    .q1(linebuf_V_2_q1),
    .address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2),
    .ce2(linebuf_V_2_ce2),
    .q2(linebuf_V_2_q2),
    .address3(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3),
    .ce3(linebuf_V_2_ce3),
    .q3(linebuf_V_2_q3)
);

conv2d_stream_conv2d_stream_Pipeline_linebuf_left_to_right grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start),
    .ap_done(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done),
    .ap_idle(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_idle),
    .ap_ready(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .out_stream_TREADY(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY),
    .out_count(out_count_load_reg_467),
    .linebuf_V_0_address0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0),
    .linebuf_V_0_ce0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0),
    .linebuf_V_0_q0(linebuf_V_0_q0),
    .linebuf_V_0_address1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address1),
    .linebuf_V_0_ce1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1),
    .linebuf_V_0_q1(linebuf_V_0_q1),
    .linebuf_V_0_address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address2),
    .linebuf_V_0_ce2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2),
    .linebuf_V_0_q2(linebuf_V_0_q2),
    .k00(k00_read_reg_425),
    .k01(k01_read_reg_420),
    .k02(k02_read_reg_415),
    .linebuf_V_1_address0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0),
    .linebuf_V_1_ce0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0),
    .linebuf_V_1_q0(linebuf_V_1_q0),
    .linebuf_V_1_address1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1),
    .linebuf_V_1_ce1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1),
    .linebuf_V_1_q1(linebuf_V_1_q1),
    .linebuf_V_1_address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address2),
    .linebuf_V_1_ce2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2),
    .linebuf_V_1_q2(linebuf_V_1_q2),
    .k10(k10_read_reg_410),
    .k11(k11_read_reg_405),
    .k12(k12_read_reg_400),
    .linebuf_V_2_address0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0),
    .linebuf_V_2_ce0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0),
    .linebuf_V_2_we0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0),
    .linebuf_V_2_d0(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0),
    .linebuf_V_2_address1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address1),
    .linebuf_V_2_ce1(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1),
    .linebuf_V_2_q1(linebuf_V_2_q1),
    .linebuf_V_2_address2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address2),
    .linebuf_V_2_ce2(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2),
    .linebuf_V_2_q2(linebuf_V_2_q2),
    .linebuf_V_2_address3(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address3),
    .linebuf_V_2_ce3(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3),
    .linebuf_V_2_q3(linebuf_V_2_q3),
    .k20(k20_read_reg_395),
    .k21(k21_read_reg_390),
    .k22(k22_read_reg_385),
    .out_stream_TDATA(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA),
    .out_stream_TVALID(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID),
    .out_stream_TKEEP(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP),
    .out_stream_TSTRB(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB),
    .out_stream_TLAST(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

conv2d_stream_conv2d_stream_Pipeline_shift_up grp_conv2d_stream_Pipeline_shift_up_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start),
    .ap_done(grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done),
    .ap_idle(grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_idle),
    .ap_ready(grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready),
    .linebuf_V_1_address0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0),
    .linebuf_V_1_ce0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0),
    .linebuf_V_1_we0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0),
    .linebuf_V_1_d0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0),
    .linebuf_V_1_address1(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1),
    .linebuf_V_1_ce1(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1),
    .linebuf_V_1_q1(linebuf_V_1_q1),
    .linebuf_V_0_address0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0),
    .linebuf_V_0_ce0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0),
    .linebuf_V_0_we0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0),
    .linebuf_V_0_d0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0),
    .linebuf_V_2_address0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0),
    .linebuf_V_2_ce0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0),
    .linebuf_V_2_we0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0),
    .linebuf_V_2_d0(grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0),
    .linebuf_V_2_q0(linebuf_V_2_q0)
);

conv2d_stream_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .k00(k00),
    .k01(k01),
    .k02(k02),
    .k10(k10),
    .k11(k11),
    .k12(k12),
    .k20(k20),
    .k21(k21),
    .k22(k22),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TDATA),
    .vld_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TKEEP),
    .vld_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TSTRB),
    .vld_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

conv2d_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TLAST),
    .vld_in(grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln49_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_ready == 1'b1)) begin
            grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_ready == 1'b1)) begin
            grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_298_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        c_reg_239 <= 7'd0;
    end else if (((icmp_ln41_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        c_reg_239 <= add_ln41_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_298_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        img_r_fu_142 <= 7'd0;
    end else if (((icmp_ln49_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        img_r_fu_142 <= img_r_2_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_298_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_count_fu_138 <= 13'd0;
    end else if (((icmp_ln49_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        out_count_fu_138 <= add_ln51_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        r_fu_122 <= 2'd0;
    end else if (((icmp_ln41_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_fu_122 <= add_ln39_reg_437;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln39_reg_437 <= add_ln39_fu_304_p2;
        r_1_reg_430 <= r_fu_122;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        k00_read_reg_425 <= k00;
        k01_read_reg_420 <= k01;
        k02_read_reg_415 <= k02;
        k10_read_reg_410 <= k10;
        k11_read_reg_405 <= k11;
        k12_read_reg_400 <= k12;
        k20_read_reg_395 <= k20;
        k21_read_reg_390 <= k21;
        k22_read_reg_385 <= k22;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        out_count_load_reg_467 <= out_count_fu_138;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_stream_TREADY_int_regslice = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_address0 = zext_ln41_fu_320_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_0_address0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_address0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_address0;
    end else begin
        linebuf_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_0_ce0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_ce0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce0;
    end else begin
        linebuf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_ce1 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce1;
    end else begin
        linebuf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_0_ce2 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_0_ce2;
    end else begin
        linebuf_V_0_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_0_d0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_d0;
    end else begin
        linebuf_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((r_1_reg_430 == 2'd0) & (icmp_ln41_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_0_we0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_0_we0;
    end else begin
        linebuf_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_address0 = zext_ln41_fu_320_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_address0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_address0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address0;
    end else begin
        linebuf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_address1 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_address1 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_address1;
    end else begin
        linebuf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_ce0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_ce0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce0;
    end else begin
        linebuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_ce1 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_ce1 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce1;
    end else begin
        linebuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_1_ce2 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_1_ce2;
    end else begin
        linebuf_V_1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_d0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_d0;
    end else begin
        linebuf_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((r_1_reg_430 == 2'd1) & (icmp_ln41_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_1_we0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_1_we0;
    end else begin
        linebuf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_address0 = zext_ln41_fu_320_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_2_address0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_address0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_address0;
    end else begin
        linebuf_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_2_ce0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce0;
    end else begin
        linebuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce1 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce1;
    end else begin
        linebuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce2 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce2;
    end else begin
        linebuf_V_2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_ce3 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_ce3;
    end else begin
        linebuf_V_2_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_V_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_2_d0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_d0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_d0;
    end else begin
        linebuf_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~(r_1_reg_430 == 2'd0) & ~(r_1_reg_430 == 2'd1) & (icmp_ln41_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        linebuf_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuf_V_2_we0 = grp_conv2d_stream_Pipeline_shift_up_fu_283_linebuf_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuf_V_2_we0 = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_linebuf_V_2_we0;
    end else begin
        linebuf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln39_fu_298_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln41_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln49_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_fu_304_p2 = (r_fu_122 + 2'd1);

assign add_ln41_fu_333_p2 = (c_reg_239 + 7'd1);

assign add_ln51_fu_362_p2 = (out_count_fu_138 + 13'd66);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_ap_start_reg;

assign grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state5);

assign grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start = grp_conv2d_stream_Pipeline_shift_up_fu_283_ap_start_reg;

assign icmp_ln39_fu_298_p2 = ((r_fu_122 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_327_p2 = ((c_reg_239 == 7'd68) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_346_p2 = ((img_r_fu_142 == 7'd66) ? 1'b1 : 1'b0);

assign img_r_2_fu_352_p2 = (img_r_fu_142 + 7'd1);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_conv2d_stream_Pipeline_linebuf_left_to_right_fu_250_out_stream_TVALID;

assign zext_ln41_fu_320_p1 = c_reg_239;

endmodule //conv2d_stream
